### ISSUE TITLE
Increase Timeout-timer after execution

### ISSUE THREAD

**Issue by ghost** [benzman81/homebridge-nukiio#1]
In some cases the lock takes longer to react as the defined timeout-timer in the nukiio-addon, which causes a negative siri-response.

**Comment by benzman81** [comment]
After some testing I found out, that it seems that the plugin actually cannot do anything about it.I tested with my dummy server and a sleep time of 15 seconds. Siri always returns after 10 seconds with the negative siri response, although it executes the action an you will get a notification about it after its success. I read a post about that these 10 seconds are hard coded for siri, but couldnt find it anymore. If someone knows a fix for it for a homebridge plugin I would be happy to implement it.
