### ISSUE TITLE
Lock/Unlock

### ISSUE THREAD

**Issue by hirbod** [benzman81/homebridge-nukiio#10]
Hi,

is there any reason why lock/unlock isn't supported? I just wanted to add siri-voice support to my nuki-lock, but this plugin isn't really useful without it. (not want to be harsh here)

**Comment by benzman81** [comment]
Hi, I think there is a bit of confusion with the note in the readme for v0.7. There have been confgiration keys "lock" and "unlock" that are no longer supported. Of course you can still lock and unlock the door with siri or the buttons ;-) Will change the readme in a second.

**Comment by hirbod** [comment]
Thank u very much. Was about to leave as I thought it is not possible :)

**Comment by benzman81** [comment]
:-)
