### ISSUE TITLE
Haustür wird "Haust%FCr"

### ISSUE THREAD

**Issue by hirbod** [benzman81/homebridge-nukiio#12]
Hi benzman81,

gerade gesehen das du aus Düsseldorf kommst. Die 3 Buttons sind jetzt sichtbar, allerdings als "Haust%FCr". Bekomme ich hier nicht das deutsche Ü rein?

**Comment by Leprechaun91** [comment]
Du kannst die Namen doch in der HomeApp selbstständig ändern.

**Comment by hirbod** [comment]
Ja, das ging. Noch ein paar Fragen, wenn es recht ist. Funktioniert soweit alles, nur ein paar "States" sind verwirrend.

"Ist die Haustür abgeschlossen?". Siri antwortet:
Nur ein Türschloss ist abgeschlossen, die anderen sind aufgeschlossen.

Die Antwort hier sollte eigentlich nur ein "Ja" sein. Aber da die Tür drei Schlossfunktionen registriert hat, kommt hier jetzt eine etwas verwirrende Antwort.

Gibt es eine Möglichkeit, den Siri-Abfragestatus irgendwie zu verbessern? (Muss ich ggf. die 3 Knöpfe umbenennen?)

**Comment by hirbod** [comment]
Edit: "add_maintainance_buttons": steht bereits auf false, also sollten die Buttons eigentlich nicht existieren, oder ich hab die config falsch verstanden.

**Comment by benzman81** [comment]
Siri: könnte sein, dass der Name eine sonderfunktion hat, versuch mal einen anderen Namen. "Eingangstür" funktioniert bei mir.

**Comment by benzman81** [comment]
Buttons: Die buttona sollten dann nicht angezeigt werden. Nimm mal bitte den eintrag raus und teste dann.

**Comment by hirbod** [comment]
Die Buttons verschwinden nicht. Weder mit false, noch mit entferntem Config-Eintrag. Ich bekomme nach Änderung des Namens immer noch die selbe Siri-Meldung.

**Comment by Leprechaun91** [comment]
Bei mir werden auch 3 buttons angelegt; aber das sind die für die Schließfunktion, für die Schließfunktion mit Türriegel und für die Option: Dauerhaft Türriegel auf.
Die anderen Buttons sind ja für das Firmwareupdate und für den reset.
Bei mir ändern sich auch die beiden Schlößer (normal und Türriegel) simultan.

Falls ich Siri nach dem Status der Tür frage, krieg ich auch nur eine entsprechende Antwort.

**Comment by hirbod** [comment]
Ich muss erwähnen, das ich keine Hook aktiv habe. Bin auf mode 0

**Comment by Leprechaun91** [comment]
Habe ich auch nicht.

**Comment by hirbod** [comment]
Sind also die maintanace buttons andere als die 3? Mir geht es nicht darum das die Buttons nicht funktionieren, sondern das Siri nicht ordentlich auf die Frage antwortet, ob die Tür offen ist. Im geschlossenen Zustand sind die Antworten korrekt.

**Comment by hirbod** [comment]
Im offenen Zustand ist ein Button auf "gesperrt" und 2 auf "entsperrt". Deswegen auch die merkwürdige Rückmeldung.

**Comment by Leprechaun91** [comment]
"to do reboot, firmware update, and to refresh all locks state"
Das sind die 3 zusätzlichen Buttons.

Merkwürdig, bei mir funktioniert alles so ohne Probleme bis jetzt

**Comment by hirbod** [comment]
Ich habe jetzt noch mal die Namen angepasst. Wenn ich expliziter Frage (ist die Tür offen geht nicht). Ist die "Haustür" offen funktioniert jedoch. Herzlichen Dank für die Rückmeldungen und euren Support. @benzman81 lass mir doch mal deine PayPal-Adresse da, dann schick ich dir nen Bier rüber für das tolle Plugin.

**Comment by benzman81** [comment]
Kannst du mal die config js ohne key und lock ids posten. Welche Namen haben die drei in der Home App?

**Comment by hirbod** [comment]
@benzman81 hauptproblem war, dass ich alles in der HomeApp gleich benannt hatte. Tür öffnen und schließen heissen jetzt beide "Haustür", Unlatch heisst jetzt "Haustürriegel".

Tür/Haustür öffnen
Tür/Haustür schließen
Haustürriegel öffnen

Frage: ist die Tür offen bezieht alle 3 Statuse ein. Ist die Tür offen, ist der Status Haustürriegel eigentlich immer auf "gesperrt"
Frage: ist die Haustür offen bezieht Haustürriegel nicht mit ein, da passt die Antwort.

Nach meinem Empfinden sollte der "Unlatch" immer den selben Status der Tür haben (das der Wert auf entsperrt steht wenn die Tür offen ist ist IMHO falsch)

**Comment by benzman81** [comment]
Was geht bei "ist die tür offen" nicht? Dann sagt siri den status zu allen drei schlössern doch, oder?

**Comment by hirbod** [comment]
Ist die Tür offen sagt: Nur ein Türschloss ist abgeschlossen, die anderen sind aufgeschlossen.

Abgeschlossen, weil der Status vom "Unlatch" immer (außer für ne Sekunde, während die Abfrage abgeschickt wird) auf gesperrt steht. Frage ich explizit nach der "Haustür", dann ist die Antwort richtig.

**Comment by hirbod** [comment]
Wie gesagt, es wäre schön, wenn es auch funktionieren würde, ohne explizit den Namen "Haustür" zu erwähnen, aber das ist jetzt eine zufriedenstellende Lösung für mich. (Wichtig für alle, die diesen Thread lesen: der Unlatch muss einen anderen Namen haben als die Haustür)

**Comment by benzman81** [comment]
Ja ok, das war erwartet, weil Alles TÜREN sind. Kannst du den satz zu deinem "Empfinden" näher erläutern :-)

**Comment by hirbod** [comment]
Das was ich mir wünsche, ist nach weiterer Überlegung (wegen den Push-Rückmeldungen von Siri) technisch sicher nicht anders zu lösen. Wie gesagt, es passt jetzt und vielen Dank @benzman81 .

Schick mir bitte noch deine PayPal-Mail (oder füg nen Donate button in die Readme ein), damit ich mich für deinen Support revanchieren kann :)

**Comment by benzman81** [comment]
@Hirbod danke für das Angebot, aber ersten mach ich das gern (manchmal dauert es auch was länger) und zweitens darf ich kein Geld annehmen ohne ein Gewerbe anzumelden und es zu versteuern, etc. .

**Comment by hirbod** [comment]
@benzman81 das ist wohl wahr. Ich hab es meistens nur mit Selbstständigen zutun (bin selbst einer) und bin es gewohnt, dass praktisch alle Open-Sourcler freiberufliche Programmierer sind :)

Trotzdem herzlichen Dank!

**Comment by benzman81** [comment]
Nope, bin Angesteller Software Developer und die OpenSource Sachen mach ich nebenher. Kein Problem.

**Comment by Leprechaun91** [comment]
Also ich habe den Unlatch und den "normalen" unterschiedlich benannt. Aber bei mir laufen beide simultan. Der einzige Unterschied sind die vielleicht 3 Sekunden in denen der Riegel gezogen wird. Bei der Frage, ob die Türen geschlossen, oder geöffnet sind, kriege ich immer das richtige Ergebnis.
Bei mir heißt die Unlach-Variante "Tür" und die normale "Tür2". Vielleicht geht es ja damit.
