### ISSUE TITLE
Problem Always unlatch

### ISSUE THREAD

**Issue by Leprechaun91** [benzman81/homebridge-nukiio#14]
Hey,

ich habe ein Problem mit der "Tür" always unlatch.
An sich ist diese super. Sie zieht den Riegel zwar nicht permanent, aber sie ist offen, wenn der Riegel gezogen und geschlossen, wenn der Riegel ausgefahren ist. So kann man den Riegel ziehen lassen, selbst wenn die Tür aufgeschlosssen ist, ohne sie erst zu schließen und wieder zu öffnen.
Allerdings ist der Riegel immer nur für ca. 3-5 Sekunden geöffnet.
Gibt es eine Möglichkeit dieses Zeitintervall zu vergrößern?

Also mit einem Delay-befehl müsste es doch auf jeden fall funktionieren, oder nicht? 
Meine js-Programmierfähigkeiten sind allerdings etwas eingeschränkter :D

**Comment by benzman81** [comment]
Nein, das geht nicht, das Nuki selbst sich um das Falle ziehen kümmert. Das Plugin sendet nur den Befehl "ziehe falle". Das selbe hast du auch mit der Nuki App. Aber bei Nuki hängt schon ein Feature request zum einstellen der zeit ;-)
