### ISSUE TITLE
[Nuki] [INFO Nuki WebHook Server] No lock found for nukiId 'xxxxxx'.

### ISSUE THREAD

**Issue by r32er** [benzman81/homebridge-nukiio#15]
everytime when i open /close the door with with the nuki app i got this error:

[Nuki] [INFO Nuki WebHook Server] No lock found for nukiId 'xxxxxx'.

lockstate mode: 1
webhookserver: is the raspberry ip
webhook port: 51827

any idea why? the lockstate is false for example although the lock is true...

**Comment by benzman81** [comment]
You seem to have a wrong nuki id configured. Is locking/unlicking via home app working? Is xxxxxxx the nuki id printed in the log, or did you just change it to hide the real id here?

**Comment by r32er** [comment]
thats the point. lock/unlock works fine with the home app/homekit.

and yes i only hide the ID.
but the ID which is in the error i dont know.

**Comment by benzman81** [comment]
Weird. Could you doublecheck if the nuki id it stated not to be found is wxactly the same as the one in the config, digit by digit? Just looked at the code and this can only happen, if there is no lock configured with this id.

**Comment by r32er** [comment]
[INFO Nuki WebHook Server] No lock found for nukiId '11380xxxxx'
in my config:06C8xxxx

the IDs are completely different. But thats what is in the nuki app in Smart lock ID. 
i Dont know. should i write the ID from the error in the config ?
"locks": [{
			"id": "11380xxxxx",

Yes it works. in the config the ID from the error log have to be. 
But in your manual is a different way. 
now it works fine with caching the lock state.

**Comment by benzman81** [comment]
Great, could you point me to the section in the readme that is wrong or confusing?

**Comment by benzman81** [comment]
Added requirements section to readme to make clear what information is needed and where to get it.

**Comment by mensa84** [comment]
Hello, I have absolutely the same problem.
I get the error "No lock found for nukiID '279....' (don't want to write the whole ID here).
But in my config file I have configured a completely different ID.
So how did you fix that problem?

My config:

```
            "platform": "NukiBridge",
            "bridge_url": "192.168.1.2:8080",
            "api_token" : "xXxXxX",
            "request_timeout_lockstate": 5000,
            "request_timeout_lockaction": 30000,
            "cache_directory": "./.node-persist/storage",
            "webhook_server_ip_or_name": "192.168.1.3",
            "webhook_port": 51827,
            "lock_state_mode": 1,
            "add_maintainance_buttons": false,
            "locks": [
                {
                    "id": "10101010",
                    "name": "Door",
                    "usesDoorLatch" : false,
                    "priority" : 1
                }
            ]
```

I used correct API token and nukiID (starting with 10), but changed it here for public.

Where is the problem?
