### ISSUE TITLE
Siri won't unlock Nuki

### ISSUE THREAD

**Issue by Cardo1** [benzman81/homebridge-nukiio#17]
I have had an unusual behaviour manifest itself over the past few days.  It may, or may not, have something to do with changes Apple is making in the run up to iOS 11.

Locking or unlocking through a HomeKit app works absolutely fine, such as Apple's Home app or the Control Centre.

However, when trying to unlock Nuki through Siri, this doesn't work.  Siri says it has executed the command, and the Home app shows the lock should be unlocking, but when looking at Homebridge the command that is sent is lock action 2 (lock!).  The Nuki bridge responds ok so no errors are shown.
When asking Siri to lock the door, it correctly sends the command and Homebridge shows the lock action 2, so the door locks.

When using the app, it correctly uses lock action 1 for unlocking, and 2 for locking.

Has anyone else seen this behaviour?  It does this on both mine and my wife's iPhones and Watches.

**Comment by Cardo1** [comment]
Actually, locking through Siri doesn't work, either.  Bizarrely, when trying to lock with Siri, it uses lock action 1.

It appears no matter what state the lock is in, and what command I use through Siri, Homebridge tries to set the lock to the current state.

**Comment by benzman81** [comment]
Hi, no problem with ios 10. did you upgrade homebridge lately? My system didnt change for months and its working like a charm.

**Comment by Cardo1** [comment]
Interesting.  My version of Homebridge is up to date.  I wonder whether a recent update has made a change that's broken control via Siri.

**Comment by Cardo1** [comment]
Reverting to Homebridge 0.4.22 seems to fix the issue.  They must have changed something.

**Comment by benzman81** [comment]
It might be the hombridge or HapJS version that changed something thats not compitible with the plugin. Feel free to contribute ;-)

**Comment by Cardo1** [comment]
Sadly, I'm not a developer, that's my wife.  She's home later today, I'll ask her to have a look. ;)

**Comment by benzman81** [comment]
Great :-)

**Comment by Cardo1** [comment]
After having a look at this, we couldn't work out the issue.  However, it appears to have been fixed with an update to HAP-nodejs.
