### ISSUE TITLE
Tür öffnen wird nicht in HomeKit angezeigt 

### ISSUE THREAD

**Issue by xMAIKx** [benzman81/homebridge-nukiio#19]
Hallo Benzman81, ich habe folgendes Problem. Tür öffnen (nur Falle ziehen) wird nicht in HomeKit aktualisiert, abschließen und aufschließen funktioniert mit etwas Verzögerung ohne Probleme. Muss die Bridge URL und die Webhook Ip gleich sein? Wo kann das Problem liegen oder muss ich die Cache Zeile mit in die Config nehmen?

"platform": "NukiBridge",
"name": "Nuki",
"bridge_url": "192.168.178.XX:XXXX",
"api_token" : "GqWv5L",
"webhook_server_ip_or_name": "192.168.178.XX",
"webhook_port": 51827,
"lock_state_mode": 1,
"add_maintainance_buttons": false,
"locks": [{
"id": "XXXXXXX",
"name": "Haustür",
"usesDoorLatch" : true,
"priority" : 1

Vielen Dank schon im Voraus.

**Comment by benzman81** [comment]
Kannst du den vorgang beschreiben (was du machst und was du wie erwartest?

Webhook ip ist die ip des rechners auf dem homebridge läuft.

**Comment by xMAIKx** [comment]
Danke für die schnelle Antwort. Ich möchte das wenn die Nukiapp meine Tür öffnet (nur Falle zieht) das sich der Schalter für Falle ziehen in HomeKit  bewegt.Das ganze funktioniert bei Tür abschließen und Tür aufschließen in HomeKit mit einer leichten Verzögerung problemlos.

**Comment by benzman81** [comment]
Das geht nicht. Über die Callbacks, die ja dafür genutzt werden, wird von Nuki immer nur der endzustand übermittelt. Dieser ist bei aufgeschlossener tür nach dem falle ziehen immer noch aufgeschlossen. Siehe issue #16.
