### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by RienduPre** [benzman81/homebridge-nukiio#20]
Hi,

I get this error, please help with a solution.

Jan 15 15:54:24 homebridge homebridge[6881]: [2018-1-15 15:54:24] [Nuki] Initializing NukiBridge platform...
Jan 15 15:54:24 homebridge homebridge[6881]: [2018-1-15 15:54:24] [Nuki] Initializing Nuki bridge 'http://192.168.1.109:8080'...
Jan 15 15:54:24 homebridge homebridge[6881]: fs.js:675
Jan 15 15:54:24 homebridge homebridge[6881]:   return binding.read(fd, buffer, offset, length, position);
Jan 15 15:54:24 homebridge homebridge[6881]:                  ^
Jan 15 15:54:24 homebridge homebridge[6881]: Error: EISDIR: illegal operation on a directory, read
Jan 15 15:54:24 homebridge homebridge[6881]:     at Object.fs.readSync (fs.js:675:18)
Jan 15 15:54:24 homebridge homebridge[6881]:     at tryReadSync (fs.js:540:20)
Jan 15 15:54:24 homebridge homebridge[6881]:     at Object.fs.readFileSync (fs.js:583:19)
Jan 15 15:54:24 homebridge homebridge[6881]:     at LocalStorage.parseFileSync (/usr/local/lib/node_modules/homebridge-nukiio/node_modules/node-persist/src/local-storage.js:642:35)
Jan 15 15:54:24 homebridge homebridge[6881]:     at LocalStorage.parseStorageDirSync (/usr/local/lib/node_modules/homebridge-nukiio/node_modules/node-persist/src/local-storage.js:596:26)
Jan 15 15:54:24 homebridge homebridge[6881]:     at LocalStorage.initSync (/usr/local/lib/node_modules/homebridge-nukiio/node_modules/node-persist/src/local-storage.js:141:14)
Jan 15 15:54:24 homebridge homebridge[6881]:     at Object.nodePersist.initSync (/usr/local/lib/node_modules/homebridge-nukiio/node_modules/node-persist/src/node-persist.js:37:32)
Jan 15 15:54:24 homebridge homebridge[6881]:     at new NukiBridge (/usr/local/lib/node_modules/homebridge-nukiio/nukibridge.js:70:18)
Jan 15 15:54:24 homebridge homebridge[6881]:     at new NukiBridgePlatform (/usr/local/lib/node_modules/homebridge-nukiio/index.js:17:23)
Jan 15 15:54:24 homebridge homebridge[6881]:     at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:304:32)
Jan 15 15:54:24 homebridge homebridge[6881]:     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
Jan 15 15:54:24 homebridge homebridge[6881]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
Jan 15 15:54:24 homebridge homebridge[6881]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Jan 15 15:54:24 homebridge homebridge[6881]:     at Module._compile (module.js:643:30)
Jan 15 15:54:24 homebridge homebridge[6881]:     at Object.Module._extensions..js (module.js:654:10)
Jan 15 15:54:24 homebridge homebridge[6881]:     at Module.load (module.js:556:32)
Jan 15 15:54:24 homebridge homebridge[6881]:     at tryModuleLoad (module.js:499:12)
Jan 15 15:54:24 homebridge homebridge[6881]:     at Function.Module._load (module.js:491:3)
Jan 15 15:54:24 homebridge homebridge[6881]:     at Function.Module.runMain (module.js:684:10)
Jan 15 15:54:24 homebridge homebridge[6881]:     at startup (bootstrap_node.js:187:16)
Jan 15 15:54:24 homebridge homebridge[6881]:     at bootstrap_node.js:608:3
Jan 15 15:54:24 homebridge systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Jan 15 15:54:24 homebridge systemd[1]: homebridge.service: Unit entered failed state.
Jan 15 15:54:24 homebridge systemd[1]: homebridge.service: Failed with result 'exit-code'.

**Comment by benzman81** [comment]
Can you show me your configuration?

**Comment by RienduPre** [comment]
Here you go.

{
            "platform": "NukiBridge",
            "bridge_url": "192.168.1.109:8080",
            "api_token": "mf3ABC",
            "cache_directory": "/home/pi",
            "locks": [
                {
                    "id": "123456789",
                    "name": "Front Door"
                }
            ],
            "name": "Nuki"
        }

**Comment by benzman81** [comment]
Must be some permission/user issue. Maybe one of these links help:
https://github.com/KhaosT/homebridge-amazondash/issues/14
https://github.com/simonlast/node-persist/issues/49
http://dlldesigner.com/illegal-operation/node-js-error-eisdir-illegal-operation-on-a-directory.php

**Comment by RienduPre** [comment]
Hi,

Unfortunately, none of the actions did solve the problem.
By the way, If I specify a wrong ip adres, the error is the same.

**Comment by RienduPre** [comment]
I tried for hours to ge this work, but jeep getting the same error.

I tested and used many many HomeBridge plugin, but never had this kind of issue.

Please help.

**Comment by benzman81** [comment]
Sorry to hear. I  am currently pretty busy. Have you tried other directories. What else have you tried? You are the first with this problem, so it must be something specific on your side.

**Comment by benzman81** [comment]
Found some time. With a simple snippet that does also use node-persist to store something I could reproduce the issue whenever the directory used was not empty or did not only contain files from node-persist. So could you please use an empty dir for cache_directory and try again?

**Comment by RienduPre** [comment]
Hi,

I have pointed the cache directory using "cache_diretory" to /home/pi/cache (which is an empty folder) but the error remains the same :-(

**Comment by benzman81** [comment]
Some good news and some bad news. Since today, I get the error, too. But still looking for a cause and solution.

**Comment by benzman81** [comment]
Ok, now I solved my exception. For me, I had the same error but from a different node module 'Hap-nodejs'. My problem was, that node-persist (which I use also for this plugin) iterates all items in the directory and they must be files. Otherwise the EISDIR error occurs. After 2 hours of trying out, I found, that in my .homebridge/persist folder that is loaded by 'Hap-nodejs' there was a hidden folder that was created from my synology disk station that is used for my homebridge. After deleting this, the error went away.

So for your problem, it will be the same. Please double check if directory is really empty and check hidden files/folders, too.

**Comment by RienduPre** [comment]
Thanks. Solved in my environment too !!!

Super  support :-)

**Comment by benzman81** [comment]
Was there a hidden file or folder?

**Comment by akyjoe** [comment]
@benzman81 Forgive me for interrupting in between the conversation. But I had a similar issue as stated above, where I had a _storage_ folder inside the _persist_ folder. _Storage_ folder contained two files similar to "_02cd4fe784b3f076c3f3f202f42093f6_" naming convention.

Upon deleting the entire _storage_ folder using `rm -R storage`, resolved the issue for me.

**Comment by sommo** [comment]
remove the storage file locate here:

/.node-persist/storage/
the storage file was:
983ee201b4891ad601fd3939fd777b0e

so do:
sudo rm -r  983ee201b4891ad601fd3939fd777b0e

find it when launch with journalctl, here's the log:
..
Aug 27 15:03:38 raspberrypi homebridge[337]: /usr/local/lib/node_modules/homebridge-nukiio/node_modules/node-persist/src/local-storage.js:647
Aug 27 15:03:38 raspberrypi homebridge[337]:             throw Error('[PARSE-ERROR] ' + file + ' does not look like a valid storage file!');
Aug 27 15:03:38 raspberrypi homebridge[337]:             ^
Aug 27 15:03:38 raspberrypi homebridge[337]: Error: [PARSE-ERROR] /.node-persist/storage/**983ee201b4891ad601fd3939fd777b0e** does not look like a valid storage file!
..

and the service start correctly
