### ISSUE TITLE
JASON parse error

### ISSUE THREAD

**Issue by danielsan1** [benzman81/homebridge-nukiio#21]
Hi, I just tried to install the Nuki plugin on my freshly installed homebidge pi.
Unfortunately (and I don't understand why) I have a JASON error, so that homebridge is not able to start. The config is more or less empty as it is a fresh install. Than I add your snippet for Nuki and I can't start homebridge anymore... When I put the snippet in JASONLint I get a parse error already with your original snippet... do you have any ideas what is causing this? (I don't see any mistakes)

Error: Parse error on line 6:
...t_lockstate": 5000, // (in ms, optional,
-----------------------^
Expecting 'STRING', got 'undefined'
 
![bildschirmfoto 2018-02-08 um 13 11 53](https://user-images.githubusercontent.com/3944456/35972444-2afe9a6e-0cd2-11e8-827d-330416a84340.png)

**Comment by benzman81** [comment]
Comments are not allowed in json. You have to remove them. The comments are just for rhe readme.
