### ISSUE TITLE
Help for webhook

### ISSUE THREAD

**Issue by Oggymator** [benzman81/homebridge-nukiio#22]
Hi,

I have a problem to configure webhook correct in the config.json.
Can you help and give me examples?

Homebridge has this config

{
  "bridge" : {
    "username" : "CD:22:3D:E3:XX:XX",
    "name" : "Homebridge",
    "pin" : "031-45-XXX",
    "port" : 51827
  },

Nuki Plugin config:

{
      "api_token" : "xxxx",
      "bridge_url" : "192.168.10.12:8080",
      "cache_directory" : "./.node-persist/storage",
      "lock_state_mode" : 0,
      "add_maintainance_buttons" : false,
      "platform" : "NukiBridge",
      "request_timeout_lockstate" : 5000,
      "locks" : [
        {
          "id" : "261XXX5",
          "usesDoorLatch" : true,
          "name" : "Tuer",
          "priority" : 1
        }
      ],
      "request_timeout_lockaction" : 30000
    }

thanks for your help.

**Comment by benzman81** [comment]
You need to add parameter: „webhook_server_ip_or_name“ with ip of the server you running homebridge on. After that startimg homebridge should print a message about registering a callback. Thats it ;-)

**Comment by Oggymator** [comment]
tried it, but homebridge crashes all the time.

config looks like this
{
      "api_token" : "XXX",
      "bridge_url" : "192.168.10.54:8080",
      "cache_directory" : "./.node-persist/storage",
      "lock_state_mode" : 0,
      "add_maintainance_buttons" : false,
      "platform" : "NukiBridge",
      "request_timeout_lockstate" : 5000,
      "webhook_server_ip_or_name": "127.0.0.1",
      "locks" : [
        {
          "id" : "26143xxxx",
          "usesDoorLatch" : true,
          "name" : "Tuer",
          "priority" : 1
        }


this said homebridge:

Mär 07 21:03:13 raspberrypideconz homebridge[26544]: [2018-3-7 21:03:13] [NukiBridge] Initializing NukiBridge platform...
Mär 07 21:03:13 raspberrypideconz homebridge[26544]: [2018-3-7 21:03:13] [NukiBridge] Initializing Nuki bridge 'http://192.168.10.54:8080'...
Mär 07 21:03:13 raspberrypideconz homebridge[26544]: [2018-3-7 21:03:13] [NukiBridge] Started server for webhooks on port '51827'.
Mär 07 21:03:13 raspberrypideconz homebridge[26544]: [2018-3-7 21:03:13] [NukiBridge] Adding webhook for plugin to bridge...
Mär 07 21:03:13 raspberrypideconz homebridge[26544]: [2018-3-7 21:03:13] [NukiBridge] Initialized Nuki bridge.
Mär 07 21:03:13 raspberrypideconz homebridge[26544]: [2018-3-7 21:03:13] [NukiBridge] Initializing platform accessory 'Tuer'...
Mär 07 21:03:13 raspberrypideconz homebridge[26544]: [2018-3-7 21:03:13] [NukiBridge] Send request to Nuki bridge 'http://192.168.10.54:8080' on '/callback/list' with '{"token":
Mär 07 21:03:13 raspberrypideconz homebridge[26544]: [2018-3-7 21:03:13] [Hue] warning: lastest version: homebridge-hue v0.8.3
Mär 07 21:03:13 raspberrypideconz homebridge[26544]: [2018-3-7 21:03:13] [Hue] deconz1: deCONZ gateway v2.5.8, api v1.0.9
Mär 07 21:03:13 raspberrypideconz homebridge[26544]: [2018-3-7 21:03:13] [Hue] deconz1: warning: not using recommended deCONZ gateway version 2.5.7
Mär 07 21:03:13 raspberrypideconz homebridge[26544]: [2018-3-7 21:03:13] [NukiBridge] Request to Nuki bridge 'http://192

**Comment by benzman81** [comment]
First of all, „127.0.0.1“ will not work, you need to enter the ip of the raspberry in your local network. Should be something like „192.168.10.xxx“ according to your nuki bridge ip.
Second, I dont see an error in your posted log. You should invlude the error ;-)

**Comment by Oggymator** [comment]
if I add the webhook home bridge crashes every time.
got only this message:

Mär 07 21:27:37 raspberrypideconz systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Mär 07 21:27:37 raspberrypideconz systemd[1]: homebridge.service: Unit entered failed state.
Mär 07 21:27:37 raspberrypideconz systemd[1]: homebridge.service: Failed with result 'exit-code'.

**Comment by benzman81** [comment]
Sorry but this is the log for the service. The first log you send was the correct one, it was only missing the lines with the error. Please send the complete homebridge log.

**Comment by Oggymator** [comment]
Mär 08 07:25:40 raspberrypideconz systemd[1]: Started Node.js HomeKit Server.
Mär 08 07:25:40 raspberrypideconz homebridge[8361]: *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
Mär 08 07:25:40 raspberrypideconz node[8361]: *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
Mär 08 07:25:40 raspberrypideconz homebridge[8361]: *** WARNING *** Please fix your application to use the native API of Avahi!
Mär 08 07:25:40 raspberrypideconz node[8361]: *** WARNING *** Please fix your application to use the native API of Avahi!
Mär 08 07:25:40 raspberrypideconz homebridge[8361]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
Mär 08 07:25:40 raspberrypideconz node[8361]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
Mär 08 07:25:40 raspberrypideconz homebridge[8361]: *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
Mär 08 07:25:40 raspberrypideconz node[8361]: *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
Mär 08 07:25:40 raspberrypideconz homebridge[8361]: *** WARNING *** Please fix your application to use the native API of Avahi!
Mär 08 07:25:40 raspberrypideconz homebridge[8361]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Mär 08 07:25:40 raspberrypideconz node[8361]: *** WARNING *** Please fix your application to use the native API of Avahi!
Mär 08 07:25:40 raspberrypideconz node[8361]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Mär 08 07:25:42 raspberrypideconz homebridge[8361]: ┌──────────────────────────────────────────────────────────────┐
Mär 08 07:25:42 raspberrypideconz homebridge[8361]: │                   npm update check failed                    │
Mär 08 07:25:42 raspberrypideconz homebridge[8361]: │             Try running with sudo or get access              │
Mär 08 07:25:42 raspberrypideconz homebridge[8361]: │             to the local update config store via             │
Mär 08 07:25:42 raspberrypideconz homebridge[8361]: │ sudo chown -R $USER:$(id -gn $USER) /home/homebridge/.config │
Mär 08 07:25:42 raspberrypideconz homebridge[8361]: └──────────────────────────────────────────────────────────────┘
Mär 08 07:25:44 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:44] Loaded plugin: homebridge-hue
Mär 08 07:25:44 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:44] Registering platform 'homebridge-hue.Hue'
Mär 08 07:25:44 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:44] ---
Mär 08 07:25:44 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:44] Loaded plugin: homebridge-nukiio
Mär 08 07:25:44 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:44] Registering platform 'homebridge-nukiio.NukiBridge'
Mär 08 07:25:44 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:44] Registering accessory 'homebridge-nukiio.NukiLock'
Mär 08 07:25:44 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:44] Registering accessory 'homebridge-nukiio.NukiBridgeMaintainanceSwitch'
Mär 08 07:25:44 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:44] ---
Mär 08 07:25:44 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:44] Loaded config.json with 0 accessories and 2 platforms.
Mär 08 07:25:44 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:44] ---
Mär 08 07:25:44 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:44] Loading 2 platforms...
Mär 08 07:25:44 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:44] [Hue] Initializing Hue platform...
Mär 08 07:25:44 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:44] [Hue] homebridge-hue v0.7.1, node v8.9.4, homebridge v0.4.38
Mär 08 07:25:44 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:44] [NukiBridge] Initializing NukiBridge platform...
Mär 08 07:25:44 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:44] [NukiBridge] Initializing Nuki bridge 'http://192.168.10.54:8080'...
Mär 08 07:25:44 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:44] [NukiBridge] Started server for webhooks on port '51827'.
Mär 08 07:25:44 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:44] [NukiBridge] Adding webhook for plugin to bridge...
Mär 08 07:25:44 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:44] [NukiBridge] Initialized Nuki bridge.
Mär 08 07:25:44 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:44] [NukiBridge] Initializing platform accessory 'Tuer'...
Mär 08 07:25:45 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:45] [NukiBridge] Send request to Nuki bridge 'http://192.168.10.54:8080' on '/callback/list' with '{"token":"s5xxx"}'.
Mär 08 07:25:45 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:45] [Hue] warning: lastest version: homebridge-hue v0.8.3
Mär 08 07:25:45 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:45] [Hue] deconz1: deCONZ gateway v2.5.8, api v1.0.9
Mär 08 07:25:45 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:45] [Hue] deconz1: warning: not using recommended deCONZ gateway version 2.5.7
Mär 08 07:25:45 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:45] [Hue] deconz1: /sensors/1: warning: ignoring unknown sensor type {"config":{"on":true,"reachable":true},"ep":1,"etag":"99a2c035b835e8cfa86cdf5384fd9fe9","manufacturerna
Mär 08 07:25:45 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:45] [Hue] deconz1: /sensors/2: warning: ignoring unknown sensor type {"config":{"on":true,"reachable":true},"ep":1,"etag":"fc38b10d6e485c267b99a2cbef1255bb","manufacturerna
Mär 08 07:25:45 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:45] [Hue] deconz1: /sensors/3: warning: unknown ZHATemperature sensor {"config":{"battery":39,"offset":0,"on":true,"reachable":true},"ep":1,"etag":"cfc967e786e1e9ace659feb8
Mär 08 07:25:45 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:45] [Hue] deconz1: /sensors/4: warning: unknown ZHAHumidity sensor {"config":{"battery":39,"on":true,"reachable":true},"ep":2,"etag":"cfc967e786e1e9ace659feb87e76f71f","man
Mär 08 07:25:45 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:45] [Hue] deconz1: /sensors/8: warning: ignoring unknown sensor type {"config":{"on":true,"reachable":false},"ep":1,"etag":"d08b9e52e6187c60377dff3293e4022e","manufacturern
Mär 08 07:25:45 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:45] [Hue] deconz1: /sensors/9: warning: ignoring unknown sensor type {"config":{"on":true,"reachable":false},"ep":1,"etag":"d08b9e52e6187c60377dff3293e4022e","manufacturern
Mär 08 07:25:45 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:45] [Hue] deconz1: /sensors/10: warning: unknown ZHAFire sensor {"config":{"battery":100,"on":true,"reachable":true},"ep":1,"etag":"933545d968a2644455641945e7df6f69","manuf
Mär 08 07:25:45 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:45] [Hue] deconz1: /sensors/11: warning: unknown ZHAFire sensor {"config":{"battery":100,"on":true,"reachable":true},"ep":1,"etag":"a640453e35a7bf5a8a8078be113053a9","manuf
Mär 08 07:25:45 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:45] [Hue] deconz1: /sensors/14: warning: unknown ZHATemperature sensor {"config":{"battery":65,"on":true,"reachable":true},"ep":1,"etag":"3fa408f180849bb4015078bda6e6ed9f",
Mär 08 07:25:45 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:45] [Hue] deconz1: /sensors/15: warning: unknown ZHAHumidity sensor {"config":{"battery":65,"on":true,"reachable":true},"ep":2,"etag":"3fa408f180849bb4015078bda6e6ed9f","ma
Mär 08 07:25:45 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:45] [Hue] deconz1: 13 accessories
Mär 08 07:25:45 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:45] [Hue] masked debug info dumped to /var/lib/homebridge/homebridge-hue.json.gz
Mär 08 07:25:45 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:45] [Hue] Initializing platform accessory 'deconz1'...
Mär 08 07:25:45 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:45] [Hue] deconz1: 2 services
Mär 08 07:25:45 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:45] [Hue] Initializing platform accessory 'TH-T_V14'...
Mär 08 07:25:45 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:45] [Hue] Initializing platform accessory 'WATER_TPV11'...
Mär 08 07:25:45 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:45] [Hue] Initializing platform accessory 'TH-T_V15'...
Mär 08 07:25:45 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:45] [Hue] Initializing platform accessory 'SMOK_V14'...
Mär 08 07:25:45 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:45] [Hue] Initializing platform accessory 'SMOK_V14 (2)'...
Mär 08 07:25:45 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:45] [Hue] Initializing platform accessory 'SMOK_V16'...
Mär 08 07:25:45 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:45] [Hue] Initializing platform accessory 'SMOK_V16 (2)'...
Mär 08 07:25:45 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:45] [Hue] Initializing platform accessory 'TH-T_V14 (2)'...
Mär 08 07:25:45 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:45] [Hue] Initializing platform accessory 'Light 1'...
Mär 08 07:25:45 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:45] [Hue] Initializing platform accessory 'Light 2'...
Mär 08 07:25:45 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:45] [Hue] Initializing platform accessory 'Light 4'...
Mär 08 07:25:45 raspberrypideconz homebridge[8361]: [2018-3-8 07:25:45] [Hue] Initializing platform accessory 'Light 6'...
Mär 08 07:25:45 raspberrypideconz homebridge[8361]: Setup Payload:
Mär 08 07:25:45 raspberrypideconz homebridge[8361]: X-HM://0023ISZB32NKD
Mär 08 07:25:45 raspberrypideconz homebridge[8361]: Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
Mär 08 07:25:45 raspberrypideconz homebridge[8361]:                                                       
Mär 08 07:25:45 raspberrypideconz homebridge[8361]:                                                       
Mär 08 07:25:45 raspberrypideconz homebridge[8361]:                                                       
Mär 08 07:25:45 raspberrypideconz homebridge[8361]:                                                       
Mär 08 07:25:45 raspberrypideconz homebridge[8361]:                                                       
Mär 08 07:25:45 raspberrypideconz homebridge[8361]:                                                       
Mär 08 07:25:45 raspberrypideconz homebridge[8361]:                                                       
Mär 08 07:25:45 raspberrypideconz homebridge[8361]:                                                       
Mär 08 07:25:45 raspberrypideconz systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Mär 08 07:25:45 raspberrypideconz systemd[1]: homebridge.service: Unit entered failed state.
Mär 08 07:25:45 raspberrypideconz systemd[1]: homebridge.service: Failed with result 'exit-code'.

**Comment by Oggymator** [comment]
I see no error.
Thats why I don't understand it.

**Comment by benzman81** [comment]
Could you post what you see when you open 

http://192.168.10.54:8080/callback/list?token=s5xxx

with your browser?

**Comment by Oggymator** [comment]
{"callbacks": [{"id": 0, "url": "http://192.168.10.54:51831/"},{"id": 1, "url": "http://192.168.10.68:51827/"},{"id": 2, "url": "http://127.0.0.1:51827/"}]}

**Comment by benzman81** [comment]
Could you execute http://192.168.10.54:8080/callback/remove?token=s5xxx&id=0 
three times in a row and try homebridge start again with correct ip set?

**Comment by Oggymator** [comment]
same problem.

for you IP 54 is Nuki Bridge
IP 68 is Pi with HomeBridge

**Comment by benzman81** [comment]
What does the output of http://192.168.10.54:8080/callback/list?token=s5xxx looks like, now?

**Comment by Oggymator** [comment]
{"callbacks": [{"id": 1, "url": "http://192.168.10.68:8080:51827/"}]}

**Comment by benzman81** [comment]
Ok this looks good, now. Could you post the log now again?

**Comment by Oggymator** [comment]
Mär 08 21:41:59 raspberrypideconz homebridge[10806]: [2018-3-8 21:41:59] [Hue] Initializing Hue platform...
Mär 08 21:41:59 raspberrypideconz homebridge[10806]: [2018-3-8 21:41:59] [Hue] homebridge-hue v0.7.1, node v8.9.4, homebridge v0.4.38
Mär 08 21:41:59 raspberrypideconz homebridge[10806]: [2018-3-8 21:41:59] [NukiBridge] Initializing NukiBridge platform...
Mär 08 21:41:59 raspberrypideconz homebridge[10806]: [2018-3-8 21:41:59] [NukiBridge] Initializing Nuki bridge 'http://192.168.10.54:8080'...
Mär 08 21:41:59 raspberrypideconz homebridge[10806]: [2018-3-8 21:41:59] [NukiBridge] Started server for webhooks on port '51827'.
Mär 08 21:41:59 raspberrypideconz homebridge[10806]: [2018-3-8 21:41:59] [NukiBridge] Adding webhook for plugin to bridge...
Mär 08 21:41:59 raspberrypideconz homebridge[10806]: [2018-3-8 21:41:59] [NukiBridge] Initialized Nuki bridge.
Mär 08 21:41:59 raspberrypideconz homebridge[10806]: [2018-3-8 21:41:59] [NukiBridge] Initializing platform accessory 'Tuer'...
Mär 08 21:42:00 raspberrypideconz homebridge[10806]: [2018-3-8 21:42:00] [Hue] warning: lastest version: homebridge-hue v0.8.3
Mär 08 21:42:00 raspberrypideconz homebridge[10806]: [2018-3-8 21:42:00] [NukiBridge] Send request to Nuki bridge 'http://192.168.10.54:8080' on '/callback/list' with '{"token":"s56xxx"}'.
Mär 08 21:42:00 raspberrypideconz homebridge[10806]: [2018-3-8 21:42:00] [Hue] deconz1: deCONZ gateway v2.5.8, api v1.0.9
Mär 08 21:42:00 raspberrypideconz homebridge[10806]: [2018-3-8 21:42:00] [Hue] deconz1: warning: not using recommended deCONZ gateway version 2.5.7
Mär 08 21:42:00 raspberrypideconz homebridge[10806]: [2018-3-8 21:42:00] [Hue] deconz1: /sensors/1: warning: ignoring unknown sensor type {"config":{"on":true,"reachable":true},"ep":1,"etag":"80e0783381b270dd2ab81d25cb07ca91","manufacturern
Mär 08 21:42:00 raspberrypideconz homebridge[10806]: [2018-3-8 21:42:00] [Hue] deconz1: /sensors/2: warning: ignoring unknown sensor type {"config":{"on":true,"reachable":true},"ep":1,"etag":"fd748cf39b9d2049e1b545a498db278c","manufacturern
Mär 08 21:42:00 raspberrypideconz homebridge[10806]: [2018-3-8 21:42:00] [Hue] deconz1: /sensors/3: warning: unknown ZHATemperature sensor {"config":{"battery":40,"offset":0,"on":true,"reachable":true},"ep":1,"etag":"b0834f894ebfa212f92192d
Mär 08 21:42:00 raspberrypideconz homebridge[10806]: [2018-3-8 21:42:00] [Hue] deconz1: /sensors/4: warning: unknown ZHAHumidity sensor {"config":{"battery":40,"on":true,"reachable":true},"ep":2,"etag":"b0834f894ebfa212f92192d6a5210f09","ma
Mär 08 21:42:00 raspberrypideconz homebridge[10806]: [2018-3-8 21:42:00] [Hue] deconz1: /sensors/8: warning: ignoring unknown sensor type {"config":{"on":true,"reachable":false},"ep":1,"etag":"d08b9e52e6187c60377dff3293e4022e","manufacturer
Mär 08 21:42:00 raspberrypideconz homebridge[10806]: [2018-3-8 21:42:00] [Hue] deconz1: /sensors/9: warning: ignoring unknown sensor type {"config":{"on":true,"reachable":false},"ep":1,"etag":"d08b9e52e6187c60377dff3293e4022e","manufacturer
Mär 08 21:42:00 raspberrypideconz homebridge[10806]: [2018-3-8 21:42:00] [Hue] deconz1: /sensors/10: warning: unknown ZHAFire sensor {"config":{"battery":100,"on":true,"reachable":true},"ep":1,"etag":"ed809b2d65c1e16882e38066ac0d999e","manu
Mär 08 21:42:00 raspberrypideconz homebridge[10806]: [2018-3-8 21:42:00] [Hue] deconz1: /sensors/11: warning: unknown ZHAFire sensor {"config":{"battery":100,"on":true,"reachable":true},"ep":1,"etag":"5e763bdb0fa46a1fe2d51a187cbda30c","manu
Mär 08 21:42:00 raspberrypideconz homebridge[10806]: [2018-3-8 21:42:00] [Hue] deconz1: /sensors/14: warning: unknown ZHATemperature sensor {"config":{"battery":62,"on":true,"reachable":true},"ep":1,"etag":"5bd9b4c44a001efcb40753197a3d35e2"
Mär 08 21:42:00 raspberrypideconz homebridge[10806]: [2018-3-8 21:42:00] [Hue] deconz1: /sensors/15: warning: unknown ZHAHumidity sensor {"config":{"battery":62,"on":true,"reachable":true},"ep":2,"etag":"5bd9b4c44a001efcb40753197a3d35e2","m
Mär 08 21:42:00 raspberrypideconz homebridge[10806]: [2018-3-8 21:42:00] [Hue] deconz1: 13 accessories
Mär 08 21:42:00 raspberrypideconz homebridge[10806]: [2018-3-8 21:42:00] [NukiBridge] Request to Nuki bridge 'http://192.168.10.54:8080' finished with status code '200' and body '{"callbacks": [{"id": 1, "url": "http://192.168.10.68:8080:51
Mär 08 21:42:00 raspberrypideconz homebridge[10806]: [2018-3-8 21:42:00] [NukiBridge] Send request to Nuki bridge 'http://192.168.10.54:8080' on '/callback/add' with '{"token":"s56xxx","url":"http://192.168.10.68:51827/"}'.
Mär 08 21:42:00 raspberrypideconz homebridge[10806]: [2018-3-8 21:42:00] [Hue] masked debug info dumped to /var/lib/homebridge/homebridge-hue.json.gz
Mär 08 21:42:00 raspberrypideconz homebridge[10806]: [2018-3-8 21:42:00] [Hue] Initializing platform accessory 'deconz1'...
Mär 08 21:42:00 raspberrypideconz homebridge[10806]: [2018-3-8 21:42:00] [Hue] deconz1: 2 services
Mär 08 21:42:00 raspberrypideconz homebridge[10806]: [2018-3-8 21:42:00] [Hue] Initializing platform accessory 'TH-T_V14'...
Mär 08 21:42:00 raspberrypideconz homebridge[10806]: [2018-3-8 21:42:00] [Hue] Initializing platform accessory 'WATER_TPV11'...
Mär 08 21:42:00 raspberrypideconz homebridge[10806]: [2018-3-8 21:42:00] [Hue] Initializing platform accessory 'TH-T_V15'...
Mär 08 21:42:00 raspberrypideconz homebridge[10806]: [2018-3-8 21:42:00] [Hue] Initializing platform accessory 'SMOK_V14'...
Mär 08 21:42:00 raspberrypideconz homebridge[10806]: [2018-3-8 21:42:00] [Hue] Initializing platform accessory 'SMOK_V14 (2)'...
Mär 08 21:42:00 raspberrypideconz homebridge[10806]: [2018-3-8 21:42:00] [Hue] Initializing platform accessory 'SMOK_V16'...
Mär 08 21:42:00 raspberrypideconz homebridge[10806]: [2018-3-8 21:42:00] [Hue] Initializing platform accessory 'SMOK_V16 (2)'...
Mär 08 21:42:00 raspberrypideconz homebridge[10806]: [2018-3-8 21:42:00] [Hue] Initializing platform accessory 'TH-T_V14 (2)'...
Mär 08 21:42:00 raspberrypideconz homebridge[10806]: [2018-3-8 21:42:00] [Hue] Initializing platform accessory 'Light 1'...
Mär 08 21:42:00 raspberrypideconz homebridge[10806]: [2018-3-8 21:42:00] [Hue] Initializing platform accessory 'Light 2'...
Mär 08 21:42:00 raspberrypideconz homebridge[10806]: [2018-3-8 21:42:00] [Hue] Initializing platform accessory 'Light 4'...
Mär 08 21:42:00 raspberrypideconz homebridge[10806]: [2018-3-8 21:42:00] [Hue] Initializing platform accessory 'Light 6'...
Mär 08 21:42:00 raspberrypideconz homebridge[10806]: Setup Payload:

**Comment by Oggymator** [comment]
seems callback has two port in IP 8080 and 51827.

[NukiBridge] Request to Nuki bridge 'http://192.168.10.54:8080' finished with status code '200' and body '{"callbacks": [{"id": 0, "url": "http://192.168.10.68:51827/"},{"id": 1, "url": "http://192.168.10.68:8080:51827/"}]}'. null

**Comment by Oggymator** [comment]
ok fixed this with the two ports, but same problem.
HomeBridges fails everytime to start.

**Comment by benzman81** [comment]
How did the port 8080 came in there? How did you fix it?

**Comment by benzman81** [comment]
Could you post the log again, but as txt file. Seems to be cut of here every time.

**Comment by Oggymator** [comment]
I tried different things, but nothing worked. So I removed the port like your 3 times ;)

I killed the other plugin now for test, so more easy.

Mär 08 22:04:45 raspberrypideconz homebridge[18133]: [2018-3-8 22:04:45] Loaded plugin: homebridge-hue
Mär 08 22:04:45 raspberrypideconz homebridge[18133]: [2018-3-8 22:04:45] Registering platform 'homebridge-hue.Hue'
Mär 08 22:04:45 raspberrypideconz homebridge[18133]: [2018-3-8 22:04:45] ---
Mär 08 22:04:46 raspberrypideconz homebridge[18133]: [2018-3-8 22:04:46] Loaded plugin: homebridge-nukiio
Mär 08 22:04:46 raspberrypideconz homebridge[18133]: [2018-3-8 22:04:46] Registering platform 'homebridge-nukiio.NukiBridge'
Mär 08 22:04:46 raspberrypideconz homebridge[18133]: [2018-3-8 22:04:46] Registering accessory 'homebridge-nukiio.NukiLock'
Mär 08 22:04:46 raspberrypideconz homebridge[18133]: [2018-3-8 22:04:46] Registering accessory 'homebridge-nukiio.NukiBridgeMaintainanceSwitch'
Mär 08 22:04:46 raspberrypideconz homebridge[18133]: [2018-3-8 22:04:46] ---
Mär 08 22:04:46 raspberrypideconz homebridge[18133]: [2018-3-8 22:04:46] Loaded config.json with 0 accessories and 1 platforms.
Mär 08 22:04:46 raspberrypideconz homebridge[18133]: [2018-3-8 22:04:46] ---
Mär 08 22:04:46 raspberrypideconz homebridge[18133]: [2018-3-8 22:04:46] Loading 1 platforms...
Mär 08 22:04:46 raspberrypideconz homebridge[18133]: [2018-3-8 22:04:46] [NukiBridge] Initializing NukiBridge platform...
Mär 08 22:04:46 raspberrypideconz homebridge[18133]: [2018-3-8 22:04:46] [NukiBridge] Initializing Nuki bridge 'http://192.168.10.54:8080'...
Mär 08 22:04:46 raspberrypideconz homebridge[18133]: [2018-3-8 22:04:46] [NukiBridge] Started server for webhooks on port '51827'.
Mär 08 22:04:46 raspberrypideconz homebridge[18133]: [2018-3-8 22:04:46] [NukiBridge] Adding webhook for plugin to bridge...
Mär 08 22:04:46 raspberrypideconz homebridge[18133]: [2018-3-8 22:04:46] [NukiBridge] Initialized Nuki bridge.
Mär 08 22:04:46 raspberrypideconz homebridge[18133]: [2018-3-8 22:04:46] [NukiBridge] Initializing platform accessory 'Tuer'...

**Comment by Oggymator** [comment]
the port for web hook must be the same port like for HomeBridge?

**Comment by benzman81** [comment]
The log is cut off again. Please post as txt file.

**Comment by benzman81** [comment]
No it must be a free port on the raspberry.

**Comment by Oggymator** [comment]
ok, seems the port was the problem.
changed it for webhook, now it crashes no more.

log is fine nuki pls see attached
[nuki.txt](https://github.com/benzman81/homebridge-nukiio/files/1794867/nuki.txt)

**Comment by benzman81** [comment]
Ok, have fun.

**Comment by Oggymator** [comment]
thanks a lot.

maybe add to your example config that the webhook must be the IP of the HomeBridge Server and that the port must be different. :)

**Comment by benzman81** [comment]
Added comments in read me.
