### ISSUE TITLE
TypeError: \"msecs\" argument must be a number

### ISSUE THREAD

**Issue by danielsan1** [benzman81/homebridge-nukiio#23]
Hi, nachdem ich homebridge neu aufsetzten musste, habe ich leider ein Problem beim Starten des Nuki Plugins. 

Homebridge fährt die Plugins hoch bis:
[Nuki] Send request to Nuki bridge 'http:\/\/192.168.188.44:8080' on '\/callback\/list' with '{\"token\":\"XYZ\"}'.  (Das ist der letzte Eintrag)
Und bricht anschließned ab mit:
Agent.connect [as createConnection] (net.js:100:12)\n    at Socket.setTimeout (net.js:385:12)\n    at Object.exports.enroll (timers.js:398:11)\nTypeError: \"msecs\" argument must be a number\n    ^\n    throw new TypeError('\"msecs\" argument must be a number');\ntimers.js:398\n

Komischerweise hat es auf dem alten System mit der gleichen config funktioniert...

Kannst du ggf. helfen?

**Comment by benzman81** [comment]
Kannst du deine config posten?

**Comment by danielsan1** [comment]
Hier ist sie:

{
  "accessories" : [

  ],
  "bridge" : {
    "username" : "CD:22:3D:E3:CE:51",
    "name" : "Homebridge",
    "pin" : "031-45-871",
    "port" : 51826
  },
  "platforms" : [
    {
      "cache_directory" : "./node-persist/storage",
      "locks" : [
        {
          "id" : "123456",
          "usesDoorLatch" : "true",
          "name" : "Eingangstür",
          "priority" : "1"
        }
      ],
      "webhook_server_ip_or_name" : "192.168.188.71",
      "api_token" : "xxxxx",
      "platform" : "NukiBridge",
      "bridge_url" : "192.168.188.44:8080",
      "request_timeout_lockacktion" : "30000",
      "lock_state_mode" : "0",
      "webhook_port" : "51827",
      "request_timeout_lockstate" : "5000",
      "name" : "Nuki",
      "add_maintenance_button" : "false"
    },
    {
      "centralSwitch" : "true",
      "username" : "yy@xx",
      "password" : "Password",
      "occupancyEnabled" : "true",
      "name" : "tado",
      "platform" : "TadoThermostat"
    }
  ]
}

**Comment by benzman81** [comment]
Die beiden timeout werte bitte nicht als string, sondern ohne Hochkomma direct als zahl. Gib bescheid obs klappt.

**Comment by danielsan1** [comment]
Super vielen Dank! Jetzt klemmt nur noch tado ;)
