### ISSUE TITLE
Webhook listening only on IPv6

### ISSUE THREAD

**Issue by willyk0** [benzman81/homebridge-nukiio#25]
On certain OSes like CentOS, node creates only IPv6 sockets even if IPv6 is disabled.

On nukibridge.js, just replace:

}).bind(this)).listen(webHookServerPort)

with

}).bind(this)).listen(webHookServerPort, "0.0.0.0")

And then it forces to listen on IPv4.

**Comment by benzman81** [comment]
Fixed with just released 0.7.7.
