### ISSUE TITLE
Webhook can't find lock ID

### ISSUE THREAD

**Issue by willyk0** [benzman81/homebridge-nukiio#26]
If Nuki Bridge sends an event to our Webhook server, I get the next message:

[NukiBridge] [INFO Nuki WebHook Server] No lock found for nukiId '_<decimal value of my nuki ID>'_. But the Nuki ID is hexadecimal!

I guess that at some point there is an unexpected hexadecimal - decimal conversion...

**Comment by willyk0** [comment]
Indeed, if you log to the console the comparison between the received ID from Bridge (apparently decimal) and the stored ID (hexadecimal) happens.

If you only have one Nuki you can do a dirty hack disabling the comparison so it always returns the first lock in the array:

```
NukiBridge.prototype._getLock = function _getLock(id) {
    for (var i = 0; i < this.locks.length; i++) {
        var lock = this.locks[i];
        //if(lock.id === id) {
            return lock;
        //}
    }
    return null;
};
```

**Comment by benzman81** [comment]
It seems that you have some kind of wrong configuration. The id received from the bridge is a number that is converted to a string by this plugin in this line https://github.com/benzman81/homebridge-nukiio/blob/0f5df2100c427e5dd3ac4848e784e925b653dba9/nukibridge.js#L117

The value in the configuration should also be a number as string (see Readme). Please also look at the Readme Requirements on how to get the correct nuke id.
