### ISSUE TITLE
No lock found for nukiID 'XXX'

### ISSUE THREAD

**Issue by mensa84** [benzman81/homebridge-nukiio#32]
Hello, can you please reopen issue #15 ?
I am getting the same error: https://github.com/benzman81/homebridge-nukiio/issues/15

**Comment by benzman81** [comment]
This is a configuration issue as stated in #15. You need to get the lock id from calling http://your-nuki-bridge-url/list?token=your-nuki-api-token in a browser. There will be the correct ID. The ID in the App is different.
