### ISSUE TITLE
Welcher Lock_State_Mode zu empfehlen?

### ISSUE THREAD

**Issue by mensa84** [benzman81/homebridge-nukiio#33]
Trotz der Beschreibung bin ich mir nicht sicher, welchen Lock_State_Mode ich verwenden soll.

Default ist ja 0, der Entwickler selbst verwendet 1 und wenn Nuki ein Firmware Update rausbringt (auf welche Version?), dann würde der Entwickler 2 verwenden. Hä?
Warum?
Ich habe aktuell  Lock FW 1.6.2. Oder ist die Bridge FW gemeint?

Ich habe nur 1 Nuki Lock an der Wohnungstür + Nuki Bridge. Mir wäre es lieber, wenn durch homebridge nicht zusätzlich noch mehr Abfragen von der Nuki Bridge and das Nuki Lock über Bluetooth ausgelöst werden, als normalerweise eh schon der Fall sind, damit die Batterien länger halten. Außerdem ist mir egal, ob der Status des Schlosses ein paar Sekunden oder ein halbe Minute verzögert ist.
Wisst ihr, welchen Modus ich verwenden soll?

**Comment by benzman81** [comment]
Readme was updated since firmware was out a long time ago, just forgot to remove the text ;-)
I'am still using mode 1 as I don't want do make additional requests.
