### ISSUE TITLE
Changelog 0.7.8?

### ISSUE THREAD

**Issue by mensa84** [benzman81/homebridge-nukiio#36]
Hello,
is there a changelog for 0.7.8?
Or is this maybe a general feature on Github? But where can I find this for homebridge-nukiio?

**Comment by mensa84** [comment]
Since 0.7.8 my complete homebridge is hanging on startup at that point:

```
Nov 23 08:15:33 Server homebridge[30220]: [2018-11-23 08:15:33] [NukiBridge] Request to Nuki bridge 'http://Nuki-Bridge:8080' finished with status code '200' and body '{"state": 1, "stateName": "locked", "batteryCritical": false, "success": true}'. null
Nov 23 08:15:33 Server homebridge[30220]: [2018-11-23 08:15:33] [NukiBridge] Lock state is isLocked = 'true' (Nuki state '1' ) with battery critical = 'false'
Nov 23 08:15:33 Server homebridge[30220]: [2018-11-23 08:15:33] [NukiBridge] Initial is locked request finished.
```

**Comment by benzman81** [comment]
Changelog is here: https://github.com/benzman81/homebridge-nukiio/blob/master/CHANGELOG.md

**Comment by benzman81** [comment]
Could you post the full homebridge log as file, please? For me it looks like the nuki plugin did everything well.

**Comment by benzman81** [comment]
Closed due to missing response.
