### ISSUE TITLE
All works but siri says there are problems

### ISSUE THREAD

**Issue by sommo** [benzman81/homebridge-nukiio#37]
I don’t know why, but when I ask to siri to open doors it do it but also after few seconds says that it can’t confirm if it has done correctly, anyone can experience this?

**Comment by benzman81** [comment]
This is because Siri expects an answer from the device in a specific time. Since Nuki Lock Actions take quite some time it mostly is out of this expected timeframe. Then you get this message. Checking with siri the state a bit afterwards reports correct status.

**Comment by sommo** [comment]
Thank you Markus, is there a way to adjust this specific time to force it waiting and send the feedback? Looking into your plugin config timeout parameters (lockstate/lockaction)?
Or these are for other purposes?

Inviato da iPhone

**Comment by benzman81** [comment]
No, these are just values for the request the plugin sends to nuki. Sadly, we cannot change anything about siri.
