### ISSUE TITLE
Enabled Homekit Notifications get fired for all doors when homebridge restarts.

### ISSUE THREAD

**Issue by produdegr** [benzman81/homebridge-nukiio#39]
Hi, I got 2 Nukis' and a bridge.
At the beginning with Nuki system I had a huge disappointment to find out that original nuki bridge is not forwarding homekit messages.
Thankfully, your homebridge plugin solved this and it works perfectly for my setup. Both doors lock and unlock. THANK YOU.
I have only one small issue: when enabling notifications on the homebridge doors, they get triggered whenever I restart the homebridge server or whenever i go to the "Accessories" section of homebridge-config-ui-x - web manager UI for homebridge.
I'm not using webhooks in my setup, doing so would it solve this?

Thanks for your time.

**Comment by benzman81** [comment]
Actually I have the same issue and have not yet had the time to look into it. Feel free to contribute.

**Comment by nicoh88** [comment]
@benzman81: Schaust du [hier](https://github.com/kdietrich/homebridge-devolo/blob/master/src/devices/HBDevoloSirenDevice.ts#L40-L42)

Beim `getServices` muss der letzte Status, am besten aus dem Cache, gesetzt werden - nicht erst beim `getState` oder ähnliches - dann weiß HomeKit dass sich der Status **nicht** geändert hat. Wenn der Status erst beim ersten `getState` gesetzt wird, ist es für HomeKit eine Statusänderung -> Notification!

Gruß Nico

**Comment by benzman81** [comment]
Fixed with 0.7.9
