### ISSUE TITLE
homebridge working-still no connection

### ISSUE THREAD

**Issue by neonightmare** [benzman81/homebridge-nukiio#4]
hi, homebridge works now, but on the iOS Device "Keine Antwort"," Dieses Gerät antwortet nicht"..

any idea, or how can I debug (logfiles are where?)

thx neo

**Comment by benzman81** [comment]
Hi, log information should appear in the log of homebridge, that is System.out in my case. Please post ir here. But dont forget to anonymize your ip, token or nukiid.

**Comment by neonightmare** [comment]
Hi, foung the output got this:

```
[Werkstatt-Türe] Getting current state...
[Werkstatt-Türe] Requesting lock state for lock XXXXXX.
[Werkstatt-Türe] Send request to Nuki bridge to /lockState with {"token":"XXXX","nukiId":"XXXXXX"}.
[Werkstatt-Türe] Request to Nuki bridge finished.
[Werkstatt-Türe] An error occured requesting lock state.
[Werkstatt-Türe] Getting current state...
[Werkstatt-Türe] Requesting lock state for lock XXXXXX.
[Werkstatt-Türe] Send request to Nuki bridge to /lockState with {"token":"XXXX","nukiId":"XXX"}.
[Werkstatt-Türe] Request to Nuki bridge finished.
[Werkstatt-Türe] An error occured requesting lock state.
[KNX] [Flynn Klima]:[Current Temperature]: Received valu
```

How ist the definition for the URL got this in config, IP-Adresse shown in the Bridge-App, got the developer status on:

```
"accessory": "Nuki",
        "bridge_url": "192.XXX.X.XXX",
        "name": "Werkstatt-Türe",
        "lock_id"  : "XXXXX",
        "api_token" : "XXXX",
        "lock_action" : "2",
        "unlock_action" : "1",
        "request_timeout_lockstate":5000,
        "request_timeout_lockaction": 30000,
        "cache_directory": "./.node-persist./storage",
        "webhook_server_port": 51827
        },
```

thx

**Comment by benzman81** [comment]
Does yor bridge url contain a port? If not, that might be the problem. If it does, have a look at http://xxx.xxx.xxx.xxx:yyyy/log?token=yourtoken. Does it seem like the requests are comming in?

**Comment by benzman81** [comment]
And please check if the URL http://xxx.xxx.xxx.xxx:yyyy/lockState?token=yourtoken&nukiId=yournukiid works in your browser.

**Comment by neonightmare** [comment]
hi, works now.

have to define like this:

 "bridge_url": "http://192.XXX.X.XXX:8080"

now it works!!

BIG THX,

**Comment by benzman81** [comment]
No problem.
