### ISSUE TITLE
Problem with Nuki Bridge Port

### ISSUE THREAD

**Issue by Nastras** [benzman81/homebridge-nukiio#40]
Hello @benzman81, I wanted to test your plugin with my Nuki. But have the following problem with the port of Nuki Bridge. No matter which port number I enter in the config and in the Nuki app always get this error:

[Log.txt](https://github.com/benzman81/homebridge-nukiio/files/3145687/Log.txt)

Here is my config:
"platforms": [
{
"platform": "NukiBridge",
"bridge_url": "192.168.178.22:9090",
"api_token" : "XXXXX",
"request_timeout_lockstate": 5000,
"request_timeout_lockaction": 30000,
"webhook_server_ip_or_name": "192.168.178.XX",
"webhook_port": XXXXX,
"cache_directory": "././var/homebridge-nukiio/node-persist/storage",
"lock_state_mode": 1,
"add_maintainance_buttons": false,
"locks": [

Do you have an idea where the problem is? It is probably a very simple mistake but I do not see -.-

Thank you!

Greeting Nastra

**Comment by Nastras** [comment]
![0FD67B90-9D5B-415D-8A21-1314AE92B777](https://user-images.githubusercontent.com/27686185/57196152-4a8cec00-6f5a-11e9-971d-e34c60364b85.jpeg)

**Comment by benzman81** [comment]
The communication with the bridge is working as the commands for callbacks to the bridge are successful in the log. This also means the token is correct. So I can imagine only two possible reasons.
1) The Nuki id is incorrect 2) The Nuki is out of range of the bridge.
You can try this in you browser and see what happens: http://192.168.178.22:9090/lockState?token=XXX&nukiId=YYY

**Comment by Nastras** [comment]
I have again compared all the data and found no error.

The reception can not be:
![IMG_0570](https://user-images.githubusercontent.com/27686185/57197429-7498db00-6f67-11e9-9670-502e8c813744.jpg)


If I adjusted this command with my data enter http://192.168.178.22:9090/lockState?token=XXX&nukiId=YYY I get no answer in the browser.

This command works and I get an answer
http: // your-nuki-bridge-url / list token = your-nuki-api-token?

Can it possibly be related that I use two Nukis 2.0 on a bridge?

I have no idea where the problem can be. -.-

**Comment by benzman81** [comment]
I think your configured nukiId is wrong. Is the id you put in the config the same you see in http: // your-nuki-bridge-url / list token = your-nuki-api-token?
The URL in the browser must return JSON, otherwise the token or nuki id is wrong, so the latter must be the issue if /list works with you token.

**Comment by Nastras** [comment]
Have you sent a PN in the SmartApfel Forum.
