### ISSUE TITLE
Homekit Version des Plugins

### ISSUE THREAD

**Issue by ScharV** [benzman81/homebridge-nukiio#44]
Hi @benzman81 vielen Dank für deine grandiose Arbeit. Ich bin seit heute auch stolzer Besitzer eines nukis und habe es nativ in HomeKit eingebunden. Nun stellt sich mir die Frage, ob es möglich wäre, eine „HomeKit“ Version von deinem Plugin zu erstellen. Ich stelle mir das so vor, dass das Schloss nativ eingebunden wird und über das Plugin Zusatzfunktionen wie die Türfalle und falls möglich der Sensor hinzukommen. So hätte man nur das native Schloss und die Türfalle als Schalter und eben nicht 3.
Viele Grüße

**Comment by benzman81** [comment]
A button to simple trigger the door latch would be easy to implement using my other plugin homebridge-http-webhooks that can call urls on push button click. The sensor is not available in the http bridge api of Nuki yet, but once it is, I guess it will be implemented in home kit, too. One additional tip is to use Siri to pull the latch with native home kit Nuki. With "Hey Siri, open foo-door" the open action will always be triggered regardless of its state.
