### ISSUE TITLE
 Still "keine Antwort"

### ISSUE THREAD

**Issue by neonightmare** [benzman81/homebridge-nukiio#5]
Sorry homebridge starts now, but still no connection to lock.

> Does yor bridge url contain a port? If not, that might be the problem. If it does, have a look at http://xxx.xxx.xxx.xxx:yyyy/log?token=yourtoken. Does it seem like the requests are comming in?

No, requests didnt arrive...

> benzman81 commented a day ago
> And please check if the URL http://xxx.xxx.xxx.xxx:yyyy/lockState?token=yourtoken&nukiId=yournukiid

No, nothing to see on the browser...

Thx

**Comment by benzman81** [comment]
Did you activate the developer mode while setting up your bridge?
Does http://xxx.xxx.xxx.xxx:yyyy/list?token=yourtoken give you the list of your locks?

**Comment by benzman81** [comment]
And please double check your token. Especially the characters case.

**Comment by neonightmare** [comment]
Hi, works now, the Lock ID on the Nuki-app was no the same as in  http://xxx.xxx.xxx.xxx:yyyy/list?token=yourtoken !! Need to put in the value of the these...

greetings and thank you.

neo

**Comment by benzman81** [comment]
Great. Have fun.
