### ISSUE TITLE
Opener: Expose "Continous Mode" and "Ring To Open" as Switch instead of Lock

### ISSUE THREAD

**Issue by flobernd** [benzman81/homebridge-nukiio#50]
Hi there,

First of all: Nice plugin!

Could you please expose the additional "Continous Mode" and "Ring To Open" locks as a Switch service instead of Locks or make this an configurable option?

Best regards

**Comment by benzman81** [comment]
I decided to use locks as this is a security issue. What is the reason or use case for using switches instead?

**Comment by flobernd** [comment]
It's just a personal preference I guess. In my opinon having just one single Lock accessory for each physical lock is way more intuitive as it represents the reality with a one to one mapping of real device to HomeKit device.

If you are concerned about security in terms that the user does not always sees an open lock icon, you could probably just always show the "main" lock as "opened" when "Continous Mode" or "Ring To Open" is active (like you do it for "Ring To Open" when "Continous Mode" is enabled). As you can't manually close a door controlled by the Nuki Opener anyways, it won't be a problem if the lock stays open in HomeKit until you disable both options.

Anyways, I can understand if you decide to not support multiple configurations.

**Comment by benzman81** [comment]
Its not about something in the UI. If anyone has your smartphone, he can activate all switches using siri without unlocking the phone. This way he could activate ringtoopen or cm and get into the house...

**Comment by flobernd** [comment]
Oh well, I did not know that. Would you mind showing the "main" lock as "closed", while one of the options is active? I think that could be a good addition anyways.

**Comment by benzman81** [comment]
Sorry for the delay. We have no influence on what the „main“ lock looks like. If one of the child locks is open, then the „main“ lock is shown open.
