### ISSUE TITLE
Opener: Expose ContactSensor service for the doorbell

### ISSUE THREAD

**Issue by flobernd** [benzman81/homebridge-nukiio#51]
Hi there,

it would be really great for automation purposes if you could expose an additional `ContactSensor` service for the Opener devices that changes state to "contact" if somebody rings the bell.

Best regards

**Comment by benzman81** [comment]
Currently not possible with the bridge.

Vote here to push this feature: https://developer.nuki.io/t/nuki-bridge-api-bell-ring-of-nuki-opener-as-trigger-for-callbacks/2557

**Comment by flobernd** [comment]
Done. Thanks!
