### ISSUE TITLE
Clean uninstall of homebridge-nukiio plugin?

### ISSUE THREAD

**Issue by mensa84** [benzman81/homebridge-nukiio#53]
Hello,

what is the correct way to do a clean uninstall of the homebridge-nukiio plugin? (It was a great help, but now I switched to nuki 2.0 and don't need the plugin anymore because of native HomeKit support of nuki).

Is it enough to just uninstall by `homebridge-nukiio` and clean up config.json?
I remember that last year that plugin also used files or entries in homebridge subdirectories `persist` or `accessories` but I am not sure where exactly. Or did that behavior already change and just uninstall and clean up config.json is enough?

**Comment by benzman81** [comment]
Never did anything else with any plugin than removing it from config.json an not installing the plugin into home bridge anymore. You could also remove the files/folders from the "cache_directory" you set or "./.node-persist/storage" if you didn't set anything other.
