### ISSUE TITLE
Opener Battery level 0% after reboot homebridge

### ISSUE THREAD

**Issue by DJay-X** [benzman81/homebridge-nukiio#56]
Hey there. 
I noticed that the battery level of the opener is always showing 0% after a homebridge reboot.
Only after opening the device for example in Eve App it instantly updates and showing the updated battery level.

Maybe something small to investigate or fix in one of the next updates.

Thanks for your works. 👍 

![ScreenFlow 2020-06-26 11_31_45](https://user-images.githubusercontent.com/3874239/85842860-a474f480-b7a0-11ea-8d75-b902c857b4ff.gif)

**Comment by benzman81** [comment]
Fixed with 0.11.1
