### ISSUE TITLE
Disable ring to open and continuous mode

### ISSUE THREAD

**Issue by jobha** [benzman81/homebridge-nukiio#57]
Have you considered adding the option to disable the ring to open and continuous mode switches?

**Comment by benzman81** [comment]
Not yet, could you explain why you like to have this?

**Comment by jobha** [comment]
Because I never use them. It would look cleaner to only have the lock in HomeKit.

**Comment by benzman81** [comment]
Ok, makes sense.

**Comment by benzman81** [comment]
Implemented in new version 0.12.0
