### ISSUE TITLE
Opener Doorbell feature

### ISSUE THREAD

**Issue by apfelflo89** [benzman81/homebridge-nukiio#62]
Do you need to activate the newly introduced Doorbell Service via a config parameter?
How does it work?

**Comment by benzman81** [comment]
It is active by default, no need to configure it. Hint: The doorbell button is not visible in Home App. You can use Eve app to define automations based on doorbell.

**Comment by netzpixel** [comment]
@benzman81 how does this work? I'd love to get a ring on my homepods with the "Homebridge Fake Doorbell" or any other way but I didn't find any doorbell option in eve.

**Comment by benzman81** [comment]
@netzpixel the option in eve is visible in automations of eve as trigger with every opener automatically. Additionally for the HomePod chime you only have to activate it in the home app in the settings of you home.
