### ISSUE TITLE
Nuki App logging off

### ISSUE THREAD

**Issue by henkhb** [benzman81/homebridge-nukiio#63]
Hey,
the Nuki App logs out, when home bridge access is in use.
This stops push notifications. I need a ring notification for the opener. 

Any chance to add this to the plugin?

Thanks

**Comment by benzman81** [comment]
Not using app login so didnt notice, yet. But I am using official API,  so I guess this works as intended. 

For the ring see https://github.com/benzman81/homebridge-nukiio/blob/master/CHANGELOG.md#0150.

You need latest lock and bridge firmware.
