### ISSUE TITLE
Support Nuki Opener ringactionState in callback as doorbell

### ISSUE THREAD

**Issue by flobernd** [benzman81/homebridge-nukiio#64]
Hi there,

I just read this point in the release notes. Should I see a ring notification in HomeKit now or how is this supposed to work?

Best regards

**Comment by benzman81** [comment]
Yes you should. As long as you have the required firmware of bridge (2.7.0 / 1.17.1)and opener (1.5.1) installed.

**Comment by flobernd** [comment]
Ah it requires the beta firmware. That explains it.

Thanks for clarification!

**Comment by flobernd** [comment]
@benzman81 I tried it again, but sadly I don't see a doorbell kind of sensor in HomeKit. I can see it in the Eve app tho. Any ideas?

**Comment by benzman81** [comment]
@flobernd thats normal and a limitation of the home app. So you need to configure automations in eve app.

**Comment by flobernd** [comment]
@benzman81 I already suspected that 😄 Thanks for confirming it!
