### ISSUE TITLE
Nuki locks twice in 360 degree setting

### ISSUE THREAD

**Issue by timwegenerDE** [benzman81/homebridge-nukiio#65]
Hi,
my nuki lock is operating with the 360 degree setting. If the door is locked and I ask siri to lock the door, nuki try to lock the door again. Then the lock becomes unresponsive because my lock can‘t be locked with 720 degree.

**Comment by benzman81** [comment]
Do you have a homebridge log output? What happens if you call http://bridgeIP:bridgePort/lock?nukiId=YourNukiLockID&token=YourToken when the door is already locked?

**Comment by timwegenerDE** [comment]
Hi,
if I call the url if nuki is already locked, it‘s locking again and then starts to blink and become unresponsive. So I think it‘s not a classic bug, but something you may can prevent in the plugin:

if (!door.isLocked)
{
 door.lock();
}
else
{
 // doNothing
}

**Comment by benzman81** [comment]
This seems to be an issue with your lock. If your lock is locked 360 it should still be able to lock a second time (if your door can do 720). Thats why it is not suppressed in the plugin. Just curious, what happens in the nuki app if you lock the lock a second time?

**Comment by timwegenerDE** [comment]
Same behavior in the app. So it‘s maybe something this plugin could do better than nuki itself? :)

**Comment by benzman81** [comment]
Ok, I decided to add a setting for this. See [here](https://github.com/benzman81/homebridge-nukiio#preventlockingifalreadylocked). Please read carefully.
