### ISSUE TITLE
Not Contain Package JSON

### ISSUE THREAD

**Issue by clipse2004** [benzman81/homebridge-nukiio#67]
Hi,
mega Plugin! Ich kannte bisher nur das von deinem Kollegen.
Zwei Kleinigkeiten habe ich allerdings.
Heute habe ich den Always Latch Knopf probiert, darauf reagiert allerdings meine Haustüre (Opener) und gleichzeitig meine Wohnungstür (Smart Lock 2). Sollte nicht eigentlich nur die Wohnungstür reagieren? Kurz danach war der Knopf für kurze Zeit auch nicht mehr erreichbar.
Und was mir brim Neustarten von HomeBridge aufgefallen ist:

[2020-10-24 5:37:21] Plugin /usr/local/lib/node_modules/homebridge-nukiio- does not contain a package.json.
[2020-10-24 5:37:21] Plugin /usr/local/lib/node_modules/homebridge-nukiioCASH does not contain a package.json

Was hat das denn zu bedeuten? Anbei noch meine Config:

 {
            "bridge_url": "http://192.168.Xxx.xx:8x8x",
            "api_token": "XxxX",
            "lock_state_mode": 1,
            "webhook_server_ip_or_name":     "http://192.168.xxx.xxx",
            "webhook_port": 51827,
   "cache_directory": "/home/pi/Nuki Cache",
            "request_timeout_lockstate": 15000,
        "request_timeout_lockaction": 45000,
            "request_timeout_other": 15000,
            "lockaction_maxtries": 3,
            "lockaction_retrydelay": 3000,
            "add_maintainance_buttons": true,
            "locks": [
                {
                    "id": "XxxxxxxxX",
                    "name": "Wohnungstür",
                    "usesDoorLatch": true,
                    "usesDoorContactSensor": true,              "preventLockingIfAlreadyLocked": false,
                    "priority": 15
                }
            ],
            "openers": [
                {
                    "id": "XxxxxxxxxX",
                    "name": "Haustür",
                    "disableRingToOpen": false,
                    "disableContinuousMode": false,
                    "priority": 15
                }
            ],
            "platform": "NukiBridge"
        }

Ich nutze Node 12.19.9 und die neueste Plugin sowie HomeBridge Version.

Danke Dir

**Comment by benzman81** [comment]
Zu den Meldungen: Die kenne ich nicht, aber aus irgendeinem Grund hast du wohl zwei Ordner `/usr/local/lib/node_modules/homebridge-nukiio-` und `/usr/local/lib/node_modules/homebridge-nukiioCASH` In deinem node modules verzeichnis. Da sollte eigentlich nur ein Ordner `/usr/local/lib/node_modules/homebridge-nukiio` sein und dieser enthält dann auch die package.js. Die anderen Ordner würde ich erstmal löschen. Evtl behebt das schon das Problem mit dem Opener und dem Lock. Falls nicht, füge bitte die Logeinträge zum Zeitpunkt des Always Unlatch Buttons von Homebridge hier ein.

**Comment by clipse2004** [comment]
Ich hatte komischerweise sogar drei Ordner da drinnen, hab ich gelöscht und Meldung ist weg :) 
Den Opener teste ich später und melde mich danach.
Eine kurze Frage noch, erfordern die Schlösser eine Bestätigung im HomeKit? Ich möchte diese Dummy Switche weglassen aber ohne Bestätigung meinerseits aufsperren.

**Comment by benzman81** [comment]
Schlösser sind sicherheitsrelevant. Alle sicherheitsrelevanten Geräte benötigen eine Bestätigung.

**Comment by clipse2004** [comment]
Sorry konnte jetzt erst testen, also schaut gut aus. Der Fehler ist bisher nicht mehr aufgetreten.
Du solltest du eine neue Version rausbringen, kannst ja gleich mal den Rechtschreibfehler und „use door sensor“ mit ausbessern :) da steht sesnor.
Ansonsten top das Plugin, hab eh grad Schwierigkeiten mit dem onboard HomeKit und der Aktualisierung.
