### ISSUE TITLE
Connection to Nuki bridge failed

### ISSUE THREAD

**Issue by panthertom** [benzman81/homebridge-nukiio#68]
Hello,

Thanks for providing the PlugIn.

Unfortunately I (interested layman!) can't access the bridge.
I have read the IP address from my Fritzbox and checked it in the Nuki App, the port is listed there as 8080.
So the URL / address is
http://192.168.178.67:8080

I also took the token from the Nuki App. This is the 6-digit token.
(I also tried the long token from the Web Nuki.io - this does not work either)

The NukiID is the ID of the opener. I did not enter the ID of the bridge anywhere. 
The bridge is connected to the network via a Fritz Access Point (mesh mode). 

1.	In the protocol I get the following message (XXXXXX stands for the token)
Process lock action '3' for Nuki lock '1B335CDA' (instance id '0') on Nuki bridge 'http://192.168.178.67:8080'.
11/9/2020, 8:46:51 AM] [NukiBridge] Send request to Nuki bridge 'http://192.168.178.67:8080' on '/lockAction' with '{"token": "XXXXXX", "nukiId": "1B335CDA", "deviceType":2, "action": "3"}'.
11/9/2020, 8:46:53 AM] [NukiBridge] Request to Nuki bridge 'http://192.168.178.67:8080' finished with status code '200' and body '{"success": false}'. null
11/9/2020, 8:46:53 AM] [NukiBridge] An error occured processing open action. Will retry now...
[11/9/2020, 8:46:56 AM] [NukiBridge] Process lock action '3' for Nuki lock '1B335CDA' (instance id '0') on Nuki bridge 'http://192.168.178.67:8080'.
11/9/2020, 8:46:56 AM] [NukiBridge] Send request to Nuki bridge 'http://192.168.178.67:8080' on '/lockAction' with '{"token": "XXXXXX", "nukiId": "1B335CDA", "deviceType":2, "action": "3"}'.
11/9/2020, 8:46:57 AM] [NukiBridge] Request to Nuki bridge 'http://192.168.178.67:8080' finished with status code '200' and body '{"success": false}'. null

2.	In the browser I get for the IP address

- With port 8080:
HTTP 400 Bad Request
- Without the port I get:
The website is not available
192.168.178.67 has rejected the connection
Try the following:
- Check connection
- Check Proxy and Firewall
ERR_CONNECTION_REFUSED

3. I opened the port 8080 for the bridge on my fritzbox.	
4. The PlugIn is running on Homebridge on a Synology.
5. Calling the mentioned link (http://your-nuki-bridge-url/list?token=your-nuki-api-token) does not work, for this I used web.Nuki.io and the Nuki App. 

Thanks for your support and help.

Thomas

![20201109 Nuki Bridge panthertom](https://user-images.githubusercontent.com/68554664/98540834-cde57700-228e-11eb-8871-9ac8076941e7.png)

**Comment by benzman81** [comment]
If `http://your-nuki-bridge-url:port/list?token=your-nuki-api-token` Does not work, then you the plugin cant work, too. Did you activate the developermode for the bridge?

**Comment by panthertom** [comment]
Hello benzman81,
Thanks for your reply.

as far as I've understood the Dev Mode is activated as shown in the APP screenshot.
- API Schnellverbindung ON
- HTTP API ON
The WEB NUKI settings are documented in the new screenshot.

If this is not enough let me know how to do this

The home bridge Settings are unchanged (DebugMode = OFF)
Thanks for your support.

Regards Thomas

**Comment by benzman81** [comment]
The plugin works with local bridge api that needs to be enabled in the bridge setting ( turn on developer mode). Nuki web api is not used here.

**Comment by panthertom** [comment]
Hi,
sorry for the dump question: How to do this?
I've already put all setting in the NUKI App to ON (see my screenshot).

There are no other settings...

Thanks for your support.
Thomas

**Comment by panthertom** [comment]
This is the result for the link in chrome:
![20201109 Nuki Bridge panthertom link](https://user-images.githubusercontent.com/68554664/98571706-1ca60780-22b5-11eb-899e-669928cb89db.png)

**Comment by benzman81** [comment]
Oh sorry, my bad :-) didnt check above. That must be it, nothing more to do. Now if you cannot reach the bridge in your browser using `http://192.168.178.67:8080/list?token=fPSpez`, the something is wrong.

**Comment by panthertom** [comment]
OK this link works. 
Result is text:
[{"deviceType": 0, "nukiId": 374504437, "name": "Eingangstüre", "firmwareVersion": "2.9.2", "lastKnownState": {"mode": 2, "state": 3, "stateName": "unlocked", "batteryCritical": false, "batteryCharging": false, "batteryChargeState": 100, "doorsensorState": 4, "doorsensorStateName": "door state unknown", "timestamp": "2020-11-09T16:48:03+00:00"}}, {"deviceType": 2, "nukiId": XXXXX, "name": "Gartentüre"}]

**Comment by panthertom** [comment]
I have to check the NUKI ID
(XXXXX)

**Comment by panthertom** [comment]
Hi Benzman81,
sorry - I have to contact you again.

I change the position of my bridge to make sure that the connection to the opener is correct and working.

1. using the link in my browser shows me:
[{"deviceType": 0, "nukiId": 374504437, "name": "Eingangstüre", "firmwareVersion": "2.9.4", "lastKnownState": {"mode": 2, "state": 3, "stateName": "unlocked", "batteryCritical": false, "batteryCharging": false, "batteryChargeState": 94, "doorsensorState": 2, "doorsensorStateName": "door closed", "timestamp": "2020-11-17T17:16:39+00:00"}}, {"deviceType": 2, "nukiId": XXXXXXXXX, "name": "Gartentüre", "firmwareVersion": "1.5.3", "lastKnownState": {"mode": 3, "state": 1, "stateName": "online", "batteryCritical": false, "timestamp": "2020-11-17T17:16:40+00:00"}}]

XXXXXXXXX = the number shown in in the result of the link

2. the state of the opener in HomeKit is "Gesperrt"

3. If I use the HomeKit Button this is the result in my home bridge status:
[11/17/2020, 6:24:03 PM] [NukiBridge] Process lock action '3' for Nuki lock 'XXXXXXXXX' (instance id '0') on Nuki bridge 'http://192.168.178.67:8080/list?token=fPSpez'.
[11/17/2020, 6:24:03 PM] [NukiBridge] Send request to Nuki bridge 'http://192.168.178.67:8080/list?token=fPSpez' on '/lockAction' with '{"token":"fPSpez","nukiId":"XXXXXXXXX","deviceType":2,"action":"3"}'.
[11/17/2020, 6:24:04 PM] [NukiBridge] Request to Nuki bridge 'http://192.168.178.67:8080/list?token=fPSpez' finished with status code '200' and body '[{"deviceType": 0, "nukiId": 374504437, "name": "Eingangstüre", "firmwareVersion": "2.9.4", "lastKnownState": {"mode": 2, "state": 3, "stateName": "unlocked", "batteryCritical": false, "batteryCharging": false, "batteryChargeState": 94, "doorsensorState": 2, "doorsensorStateName": "door closed", "timestamp": "2020-11-17T17:16:39+00:00"}}, {"deviceType": 2, "nukiId": XXXXXXXXX, "name": "Gartentüre", "firmwareVersion": "1.5.3", "lastKnownState": {"mode": 3, "state": 1, "stateName": "online", "batteryCritical": false, "timestamp": "2020-11-17T17:16:40+00:00"}}]'. null
[11/17/2020, 6:24:04 PM] [NukiBridge] HomeKit state change complete.

4. But unfortunately the opener shows no reaction.

5. If I user the Nuki App or WebNuki everything works fine.
At Bridge Token "fPSpez" is used.

6. I tried to get access to my nuki smart lock, using the corresponding data - it does not work ether.
 
Any Ideas?

Thanks for your help
Kind Regards 
Thomas

**Comment by benzman81** [comment]
Can you sho me your config?

**Comment by panthertom** [comment]
Hi, have you received my config data? Please drop me a line.
Or if you need more information
Thanks for your support

**Comment by benzman81** [comment]
No, no data of you config here.

**Comment by benzman81** [comment]
Die Bridge URL (bridge_url) in der PluginConfig muss so lauten: `http://192.168.178.67:8080`
Ohne irgendwas dahinter.

**Comment by panthertom** [comment]
Du bist Mein Held! Kaum macht man es richtig - schon funktioniert's.
Nochmals Danke für das PlugIn und die Unterstützung. Ich nehme jetzt meine Configuration wieder raus.

**Comment by benzman81** [comment]
gern.
