### ISSUE TITLE
Multi-Language support and behaviour

### ISSUE THREAD

**Issue by Nivlac7** [benzman81/homebridge-nukiio#76]
Hi,

Great work, thanks for it!

As improvement, would be nice to be able to change the "ALWAYS  Unlatch" and "Unlatch Allowed" names to have a multi-language support. 
(EDIT) OK found how to change it in Home app, though not straightforward...

Regarding bahaviour, would be great to have different call to siri for the 3 actions:
Lock the door -> would lock it
Unlock the door -> would just unlock it
Open the door -> would unlock and unlatch (if latch is activated)

Thanks!

**Comment by benzman81** [comment]
For 1) edit in the home app as you allready did.
For 2) Not possible. Apple sadly only knows lock and unlock.

**Comment by benzman81** [comment]
Hint: since there are two locks. Name the one to always unlatch only „latch“ and you can lock the other one by siri using „unlock lockone“ oder „lock lockone“ and the other one by „unlock latch.

**Comment by Nivlac7** [comment]
Thanks for your prompt reply!

Indeed it works great the way you explained. Great homekit integration 🙂
