### ISSUE TITLE
Opener: Doorbell Switch is not working

### ISSUE THREAD

**Issue by DonBlackBoxo** [benzman81/homebridge-nukiio#80]
Hi,

i have the Plugin running with my opener and everything is working fine. Only the Doorbell switch does nothing. When i set the switch in the Home App then you see „Switch state for '12345678'...“ and nothing happens. When you look at the Nuki App youu see that the switch was not switched.

thanks,
Martin
![0D5D0753-F51D-4556-9D7D-2CDDB8B40AD6](https://user-images.githubusercontent.com/81435202/112668755-29d82300-8e5f-11eb-871a-28ada605969e.jpeg)

**Comment by benzman81** [comment]
What do you mean by „does nothing? Does the state in the home app of the button switch its state?

**Comment by DonBlackBoxo** [comment]
The switch in the home app is working fine. You can toggle and it's changing its state. At the same moment when you toggle you also see the above described log entry in the Homebridge log but in Nuki the state does not change....

**Comment by benzman81** [comment]
Ah, I see. You expect to see this state reflected the Nuki App. This doent work as Nuki Bridge does not have an API to change it. The switch is to turn off the doorbell in Homekit, so that your homepods do not ring.

**Comment by DonBlackBoxo** [comment]
Ahhhhhhhhh :) That explains everything! Thank you for the clarification. If Nuki does not offer an API it cannot work 🤷‍♂️

Thank you for your swift reply and for your great job with this homebridge plugin
