### ISSUE TITLE
This Plugin slows down Homebridge

### ISSUE THREAD

**Issue by lukepistrol** [benzman81/homebridge-nukiio#81]
I’m regularly seeing this in the Homebridge logs. Plug-in runs in a Child Bridge. 

> This Plugin slows down Homebridge. The read handler for the characteristic 'Lock current state' was slow to respond. See https://git.io/JtMGR for more info

**Comment by benzman81** [comment]
Sorry for the very late reply, I haven been pretty busy.
This can happen using `lock_state_mode` with value `0` and is due the response time of the bridge. With `lock_state_mode` value `1` you should be able to avoid this.
