### ISSUE TITLE
Ability to know which user open the Smart Lock

### ISSUE THREAD

**Issue by cjournet** [benzman81/homebridge-nukiio#82]
Hello,

I use this feature with IFTTT but maybe it can be implemented in your plugin.
I explain the case, in IFTTT you can create a trigger when a specific user open the Lock. For example the User Toto using Keypad to open the lock. And from what I have found for the moment, it's only possible to have it with IFTTT for the moment.

Having this kind of information can help making great scenario, for example if my kids is coming back to the house using the keypad, I can start music or a light etc.

Do you think is possible in the API? Having this information in Homekit with performant app like Controller?

Thanks

**Comment by benzman81** [comment]
Not possible due to API limitatione, see here https://developer.nuki.io/t/lock-unlock-response-misses-who-did-that-action/10678
