### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by kpagidas** [benzman81/homebridge-nukiio#83]
15/07/2021, 12:38:14Nukiio Bridge starting
15/07/2021, 12:38:23Nukiio BridgeLoaded plugin 'homebridge-nukiio'
15/07/2021, 12:38:23Nukiio BridgeLoading 1 platforms...
15/07/2021, 12:38:23Nukiio BridgeNukiBridgeInitializing Nuki bridge 'http://172.16.0.10:80'...
15/07/2021, 12:38:23Nukiio BridgeNukiBridgeStarted server for webhooks on port '8080'.
15/07/2021, 12:38:23Nukiio BridgeNukiBridgeAdding webhook for plugin to bridge...
15/07/2021, 12:38:23Nukiio BridgeNukiBridgeInitialized Nuki bridge.
15/07/2021, 12:38:23Nukiio BridgeBridge is running on port 56826.
15/07/2021, 12:38:23Nukiio BridgeNukiBridgeSend request to Nuki bridge 'http://172.16.0.10:80' on '/lockState' with '{"nukiId":"1AB05F35","deviceType":0,"ts":"2021-07-15T09:38:23Z","rnr":50155,"hash":"fc4332ae3392a456b8cc4784e4988f2e9ce4077c2d447e50c9ef405a49043412"}'.
15/07/2021, 12:38:23Nukiio BridgeNukiBridgeRequest to Nuki bridge 'http://172.16.0.10:80' finished with status code '-1' and body 'undefined'. Error: connect ECONNREFUSED 172.16.0.10:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '172.16.0.10',
  port: 80
}
15/07/2021, 12:38:24Nukiio BridgeNukiBridgeRequest for lock state aborted. This is no problem and might happen due to canceled request or due to long response time of the Nuki bridge. Using cached value isLocked = 'true'.
15/07/2021, 12:38:24Nukiio BridgeNukiBridgeInitial is locked request finished.
15/07/2021, 12:38:24Nukiio BridgeNukiBridgeSend request to Nuki bridge 'http://172.16.0.10:80' on '/callback/list' with '{"ts":"2021-07-15T09:38:24Z","rnr":34527,"hash":"567b922164fbee98b0a843e73d2a6ed4d0565674bfc1c5d26a778f3d5e1a7ea1"}'.
15/07/2021, 12:38:24Nukiio BridgeNukiBridgeRequest to Nuki bridge 'http://172.16.0.10:80' finished with status code '-1' and body 'undefined'. Error: connect ECONNREFUSED 172.16.0.10:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '172.16.0.10',
  port: 80
}
15/07/2021, 12:38:33Nukiio Bridge starting

**Comment by benzman81** [comment]
Seems like you use an IP or port that ist not reachable. Whats happens in a browser when you call `http://172.16.0.10:80/info?token=yourtokenhere` ?

**Comment by kpagidas** [comment]
Thank for your answer.


Nothing happens and the page does not load

**Comment by benzman81** [comment]
Than that is probably not the IP and/or port of the Nuki Bridge. Did you enabled
 the developer mode of the bridge?

**Comment by kpagidas** [comment]
Yes!


What am i missing? 🙄 




This the old IP..

**Comment by benzman81** [comment]
So it is working now?

**Comment by kpagidas** [comment]
Νο,it is not working.. 

Any advice?

**Comment by benzman81** [comment]
If it is not callable via URL in a browser, than you have the wrong IP or port. Try to get it from the bridge settings or your router.

**Comment by kpagidas** [comment]
With the following 

http://172.16.0.10:8080/list?token=your-nuki-api-token


I received 
Http 401 Unauthorized

How to authorise it?

**Comment by benzman81** [comment]
Did you use your API token?

**Comment by kpagidas** [comment]
[{"deviceType": 0, "nukiId": 447766325, "name": "Garage", "firmwareVersion": "2.10.8", "lastKnownState": {"mode": 2, "state": 3, "stateName": "unlocked", "batteryCritical": false, "batteryCharging": false, "batteryChargeState": 100, "doorsensorState": 4, "doorsensorStateName": "door state unknown", "timestamp": "2021-07-15T12:59:15+00:00"}}]


Ok , after I use my API TOKEN , everything ok , I am in :)


Now what ?

**Comment by benzman81** [comment]
Check your configuration. My guess is, that you did not include the correct port in the server url parameter.

**Comment by benzman81** [comment]
Since there was no reply anymore. Is this solved or obsolete?

**Comment by benzman81** [comment]
closed due to no response
