### ISSUE TITLE
Nuki Smartlock 3.0 Pro DeviceType 4

### ISSUE THREAD

**Issue by apfelflo89** [benzman81/homebridge-nukiio#85]
Hey just wanna let you know that Nuki Startblock 3.0 Pro has the deviceType 4. I was just trying to use your plugin and other Nuki integrations and noticed it wouldn't accept the lock and unlock commands when using it with my bridge. 

I noticed that Nuki did not documented that fact so far

**Comment by benzman81** [comment]
Documentation was updated: https://developer.nuki.io/page/nuki-bridge-http-api-1-13/4/

Implementation will follow.

**Comment by benzman81** [comment]
Implemented new configuration `deviceType` to locks. Possible settings are listed in the readme. This is a blind implementation as I do not own a smart lock 3.0.
