### ISSUE TITLE
Smart Door Problems

### ISSUE THREAD

**Issue by csoprano** [benzman81/homebridge-nukiio#86]
HI,
i can't get the plugin to work with my smart door. the accessory is added but I cannot interact with it in any way. in the console I get this:

[1/21/2022, 9:37:01 AM] [NukiBridge] Request to Nuki bridge 'http://192.168.178.35:8080' finished with status code '-1' and body 'undefined'. Error: connect EHOSTDOWN 192.168.178.35:8080 - Local (192.168.178.23:63051)
    at internalConnect (net.js: 920: 16)
    at defaultTriggerAsyncIdScope (internal / async_hooks.js: 429: 12)
    at net.js: 1008: 9
    at processTicksAndRejections (internal / process / task_queues.js: 75: 11) {
  errno: -64,
  code: 'EHOSTDOWN',
  syscall: 'connect',
  address: '192.168.178.35',
  port: 8080
}
[1/21/2022, 9:37:01 AM] [NukiBridge] Request for lock state aborted. This is no problem and might happen due to canceled request or due to long response time of the Nuki bridge. Using cached value isLocked = 'false'.
[1/21/2022, 9:37:01 AM] [NukiBridge] Request for lock state aborted. This is no problem and might happen due to canceled request or due to long response time of the Nuki bridge. Using cached value isLocked = 'false'.
[1/21/2022, 9:37:01 AM] [NukiBridge] Request for lock state aborted. This is no problem and might happen due to canceled request or due to long response time of the Nuki bridge. Using cached value isLocked = 'false'.
[1/21/2022, 9:41:02 AM] [NetworkPresence] [Iphone Valentina] - disconnected from the network (mac: 52: 7d: 3e: 07: 8b: 85 | ip: 192.168.178.28 | hostname :? )
My configuration is:

  "bridge_url": "****:port",
            "api_token": "*****",
            "api_token_hashed": false,
            "lock_state_mode": 2,
            "webhook_port": 51827,
            "request_timeout_lockstate": 15000,
            "request_timeout_lockaction": 45000,
            "request_timeout_other": 15000,
            "lockaction_maxtries": 3,
            "lockaction_retrydelay": 3000,
            "add_maintainance_buttons": false,
            "locks": [
                {
                    "id": "*****",
                    "name": "Porta",
                    "usesDoorContactSensor": true,
                    "deviceType": 3
                }
            ],
            "platform": "NukiBridge"

Furthermore, the get call to this url http: // your-nuki-bridge-url / list? token = your-nuki-api-token to receive port id times out.
Could you help me solve it? thank you

**Comment by csoprano** [comment]
> HI, i can't get the plugin to work with my smart door. the accessory is added but I cannot interact with it in any way. in the console I get this:
> 
> [1/21/2022, 9:37:01 AM] [NukiBridge] Request to Nuki bridge 'http://192.168.178.35:8080' finished with status code '-1' and body 'undefined'. Error: connect EHOSTDOWN 192.168.178.35:8080 - Local (192.168.178.23:63051) at internalConnect (net.js: 920: 16) at defaultTriggerAsyncIdScope (internal / async_hooks.js: 429: 12) at net.js: 1008: 9 at processTicksAndRejections (internal / process / task_queues.js: 75: 11) { errno: -64, code: 'EHOSTDOWN', syscall: 'connect', address: '192.168.178.35', port: 8080 } [1/21/2022, 9:37:01 AM] [NukiBridge] Request for lock state aborted. This is no problem and might happen due to canceled request or due to long response time of the Nuki bridge. Using cached value isLocked = 'false'. [1/21/2022, 9:37:01 AM] [NukiBridge] Request for lock state aborted. This is no problem and might happen due to canceled request or due to long response time of the Nuki bridge. Using cached value isLocked = 'false'. [1/21/2022, 9:37:01 AM] [NukiBridge] Request for lock state aborted. This is no problem and might happen due to canceled request or due to long response time of the Nuki bridge. Using cached value isLocked = 'false'. [1/21/2022, 9:41:02 AM] [NetworkPresence] [Iphone Valentina] - disconnected from the network (mac: 52: 7d: 3e: 07: 8b: 85 | ip: 192.168.178.28 | hostname :? ) My configuration is:
> 
> "bridge_url": "****:port", "api_token": "_****", "api_token_hashed": false, "lock_state_mode": 2, "webhook_port": 51827, "request_timeout_lockstate": 15000, "request_timeout_lockaction": 45000, "request_timeout_other": 15000, "lockaction_maxtries": 3, "lockaction_retrydelay": 3000, "add_maintainance_buttons": false, "locks": [ { "id": "****_", "name": "Porta", "usesDoorContactSensor": true, "deviceType": 3 } ], "platform": "NukiBridge"
> 
> Furthermore, the get call to this url http: // your-nuki-bridge-url / list? token = your-nuki-api-token to receive port id times out. Could you help me solve it? thank you

**Comment by csoprano** [comment]
> HI, i can't get the plugin to work with my smart door. the accessory is added but I cannot interact with it in any way. in the console I get this:
> 
> [1/21/2022, 9:37:01 AM] [NukiBridge] Request to Nuki bridge 'http://192.168.178.35:8080' finished with status code '-1' and body 'undefined'. Error: connect EHOSTDOWN 192.168.178.35:8080 - Local (192.168.178.23:63051) at internalConnect (net.js: 920: 16) at defaultTriggerAsyncIdScope (internal / async_hooks.js: 429: 12) at net.js: 1008: 9 at processTicksAndRejections (internal / process / task_queues.js: 75: 11) { errno: -64, code: 'EHOSTDOWN', syscall: 'connect', address: '192.168.178.35', port: 8080 } [1/21/2022, 9:37:01 AM] [NukiBridge] Request for lock state aborted. This is no problem and might happen due to canceled request or due to long response time of the Nuki bridge. Using cached value isLocked = 'false'. [1/21/2022, 9:37:01 AM] [NukiBridge] Request for lock state aborted. This is no problem and might happen due to canceled request or due to long response time of the Nuki bridge. Using cached value isLocked = 'false'. [1/21/2022, 9:37:01 AM] [NukiBridge] Request for lock state aborted. This is no problem and might happen due to canceled request or due to long response time of the Nuki bridge. Using cached value isLocked = 'false'. [1/21/2022, 9:41:02 AM] [NetworkPresence] [Iphone Valentina] - disconnected from the network (mac: 52: 7d: 3e: 07: 8b: 85 | ip: 192.168.178.28 | hostname :? ) My configuration is:
> 
> "bridge_url": "****:port", "api_token": "_****", "api_token_hashed": false, "lock_state_mode": 2, "webhook_port": 51827, "request_timeout_lockstate": 15000, "request_timeout_lockaction": 45000, "request_timeout_other": 15000, "lockaction_maxtries": 3, "lockaction_retrydelay": 3000, "add_maintainance_buttons": false, "locks": [ { "id": "****_", "name": "Porta", "usesDoorContactSensor": true, "deviceType": 3 } ], "platform": "NukiBridge"
> 
> Furthermore, the get call to this url http: // your-nuki-bridge-url / list? token = your-nuki-api-token to receive port id times out. Could you help me solve it? thank you

**Comment by benzman81** [comment]
If you can't call `http://192.168.178.35:8080/list?token=yourToken` then there must be something wrong in your setup. Wrong IP, wrong port or wrong token.

**Comment by csoprano** [comment]
Image removed ;-)

I get the data to be entered in the configuration from here. it's correct?

**Comment by benzman81** [comment]
I removed the image because of data security.

Yes, thats correct. What exactly happens in the browser, when you call `http://192.168.178.35:8080/list?token=yourToken`?

**Comment by csoprano** [comment]
sorry i forgot to blank out the data.
the call remains pending and after a while it times out.

**Comment by benzman81** [comment]
Then you should consult the nuki support. I don't know how I can help anymore. If the bridge url like above is not callable, then the plugin cannot connect as well.
