### ISSUE TITLE
Smart Door Unlatch and lock state problems

### ISSUE THREAD

**Issue by csoprano** [benzman81/homebridge-nukiio#90]
Hi everyone,
I have correctly configured my smart door.
I have enabled the uses door latch option.
When the "Allowed Unlatch" switch is activated, the door opens without problems.
However, I cannot understand why once opened in the home app it immediately blocks and says closed when it is still open.
Another thing that seems not to work is the update of the status and the status of the sensor.
This is my setup:
  "bridge_url": "xxxxxxxxxx",
            "api_token": "xxxxxxxxx",
            "api_token_hashed": false,
            "lock_state_mode": 0,
            "webhook_port": xxxxxx,
            "request_timeout_lockstate": 15000,
            "request_timeout_lockaction": 45000,
            "request_timeout_other": 15000,
            "lockaction_maxtries": 3,
            "lockaction_retrydelay": 3000,
            "add_maintainance_buttons": false,
            "locks": [
                {
                    "id": "xxxxxxx",
                    "name": "Door",
                    "usesDoorLatch": true,
                    "usesDoorContactSensor": true,
                    "preventLockingIfAlreadyLocked": false,
                    "deviceType": 3
                }
            ],
            "platform": "NukiBridge"

Hope you can help me.
Thanks

**Comment by benzman81** [comment]
1. The button to unlatch the door will always switch back to closed right away, and so does your door latch. There is no state „latch is open“.
2. For the status update of the door and the sensor you habe to explain what is not working and also post anonomized logs.

**Comment by csoprano** [comment]
Hi @benzman81 ,

I am still having problems with updating the status of the door sensor. Basically if I open the door the sensor does not update immediately but it takes at least a minute to realise that the door is open and the same thing happens when I close.

If I open nuki app and then go back to home app it updates, it's like it's not communicating with the bridge.

Can you help me figure out how to fix it?
Thanks in advance

**Comment by benzman81** [comment]
Well, if communication is the problem, I dont know how much I can help. What does the homebridge log tell you, when this happens?

**Comment by benzman81** [comment]
closed due to no response.
