### ISSUE TITLE
How to enable Bridge developer mode?

### ISSUE THREAD

**Issue by mensa84** [benzman81/homebridge-nukiio#91]
Hello,

how can one enable Nuki Bridge "Developer Mode"? Is it the same as "HTTP API"?
I can't find a developer mode in the app to activate and also no manual via Google.

**Comment by benzman81** [comment]
Sorry for the late answer. It is the HTTP API, so you can set ist, when you menage the bridge in the App nesr the Wifi settings according to this article https://support.nuki.io/hc/de/articles/360016174257-Ersteinrichtung-deiner-Nuki-Bridge
