### ISSUE TITLE
Can the opener be used without a bridge using this plugin?

### ISSUE THREAD

**Issue by bosco90** [benzman81/homebridge-nukiio#94]
I've just installed a Smart lock 3.0 Pro and it works great, this mean I don't have a bridge.

Can I buy the opener alone and use it with this plugin (maybe using the "built in bridge" of the lock 3.0 pro)

Thanks a lot!

**Comment by benzman81** [comment]
This plugin uses the http api of the bridge. The Smart lock 3.0 Pro does not have any local api to use, yet. And the needs definetly a bridge to be reachable. It will not connect to Smart lock 3.0 Pro as far as I follow the developer forum of nuki.

**Comment by bosco90** [comment]
Thanks for your reply! Just to be clear, I don't want to connect the Pro 3 to a virtual bridge but the Opener, it's this possible?

**Comment by benzman81** [comment]
@bosco90 there is no official virtual bridge. For this plugin, you need to have the offizial bridge with the http api / developer mode enabled.

**Comment by bosco90** [comment]
Oooh sorry! I've confused your plugin with another one, my bad!!!

**Comment by benzman81** [comment]
np
