### ISSUE TITLE
Bridge added, but nothing appears in Homekit

### ISSUE THREAD

**Issue by Myth0zz** [benzman81/homebridge-nukiio#97]
Hello, and thank you for this plugin.

I added it to my HOOBS, with no problems. I found the nukiID of my opener and Nuki Lock. I added this in config:

{
    "platform": "homebridge-nukiio",
    "bridge_url": "http://192.168.152.210:8080",
    "api_token": "556144",
    "locks": [
        {
            "id": "435352773",
            "name": "Front Door",
            "usesDoorLatch": true,
            "usesDoorContactSensor": true,
            "preventLockingIfAlreadyLocked": true,
            "priority": 1,
            "deviceType": 0
        }
    ],
    "openers": [
        {
            "id": "861041802",
            "name": "Main Opener",
            "disableRingToOpen": false,
            "disableContinuousMode": false
        }
    ]
}

However nothing appears in my Homekit. Is there a problem somewhere? My HOOBS log says:

MNukiio Bridge starting
4/28/2023, 5:36:51 PMNukiio BridgeLoaded plugin 'homebridge-nukiio'
4/28/2023, 5:36:51 PMNukiio BridgeLoading 1 platforms...
4/28/2023, 5:36:51 PMNukiio BridgeBridge is running on port 51886.

Any help would be appreciated.

**Comment by benzman81** [comment]
Did you solve it? Don't know how it works in HOOBS. Any other log entries? There should be more later on.

**Comment by mfreund88** [comment]
I have the same issue. Nukiio configured, no error message when rebooting HB, Device NOT shown in Homekit. Devices shown in Homebridge Device overview.

**Comment by benzman81** [comment]
@mfreund88 are you also using HOOBS? I can't reproduce this. Could you share an anonymized log with the entries of the plugin on start?

**Comment by benzman81** [comment]
closed due to no response.
