### ISSUE TITLE
Replace Nuki smart lock without loosing HomeKit automations?

### ISSUE THREAD

**Issue by mensa84** [benzman81/homebridge-nukiio#99]
Hi,

is it possible to replace my Nuki smart lock (switching from 2.0 to 3.0) in Homebridge without loosing my HomeKit automations?
How to do that, that HomeKit thinks it is still the same device?

**Comment by benzman81** [comment]
Not sure about it. Never did that.

**Comment by mensa84** [comment]
Maybe an idea how it could work?

**Comment by benzman81** [comment]
Maybe it works automatically if you just change the id to your new lock. Just setup a second homebridge and give it a try.

**Comment by benzman81** [comment]
Could you post your solution to support others with the same question?

**Comment by mensa84** [comment]
Yes, but it will take some time until m bew Nuki will arrive.

**Comment by mensa84** [comment]
> Maybe it works automatically if you just change the id to your new lock. Just setup a second homebridge and give it a try.

That's the solution! It works by just replacing the Nuki ID. Thanks a lot! That saved a lot of work!

**Comment by benzman81** [comment]
Great, thanks for the feedback.
